Repository consta-design-system/uikit, pull requests merged in 2020-07, with the labels that each got.

#237 fix(IconBag): fix color
  src/icons/IconBag/IconBag_size_m.svg
  src/icons/IconBag/IconBag_size_m.tsx
  src/icons/IconBag/IconBag_size_s.svg
  src/icons/IconBag/IconBag_size_s.tsx
  src/icons/IconBag/IconBag_size_xs.svg
  src/icons/IconBag/IconBag_size_xs.tsx
Labels: bug

#224 chore(tslib): update -> 13.0.0
  package.json
  yarn.lock
Labels: dependencies

#216 Feat/154 add icon size
  src/components/Button/Button.tsx
  src/components/ChoiceGroup/ChoiceGroup.tsx
  src/components/ChoiceGroup/Item/ChoiceGroup__item.tsx
  src/components/ProgressSpin/ProgressSpin.tsx
  src/components/Tabs/Tab/Tabs-Tab.tsx
  src/components/Tabs/Tabs.md
  src/components/Tabs/Tabs.tsx
  src/components/TextField/TextField.tsx
  src/components/User/User.tsx
  src/utils/getSizeByMap.test.tsx
  src/utils/getSizeByMap.tsx
Labels: feature

#241 feat(Theme): add ref
  src/components/Theme/Theme.tsx
Labels: feature

#245 feat(icons): add new icons IconUnsort
  src/fileIcons/FileIcon/stories/FileIcons.stories.tsx
  src/icons/Icon/stories/Icons.stories.tsx
  src/icons/IconUnsort/IconUnsort.tsx
  src/icons/IconUnsort/IconUnsort_size_m.svg
  src/icons/IconUnsort/IconUnsort_size_m.tsx
  src/icons/IconUnsort/IconUnsort_size_s.svg
  src/icons/IconUnsort/IconUnsort_size_s.tsx
  src/icons/IconUnsort/IconUnsort_size_xs.svg
  src/icons/IconUnsort/IconUnsort_size_xs.tsx
Labels: feature

#244 fix(iconAlignRight): replace wrong svg
  src/icons/IconAlignRight/IconAlignRight_size_m.svg
  src/icons/IconAlignRight/IconAlignRight_size_m.tsx
  src/icons/IconAlignRight/IconAlignRight_size_s.svg
  src/icons/IconAlignRight/IconAlignRight_size_s.tsx
  src/icons/IconAlignRight/IconAlignRight_size_xs.svg
  src/icons/IconAlignRight/IconAlignRight_size_xs.tsx
Labels: bug

#202 docs(button): add new docs for button
  .storybook/config.js
  .storybook/main.js
  package.json
  src/components/Button/Button.stories.tsx
  src/components/Button/stories/Button.mdx
  src/components/Button/stories/Button.stories.tsx
  src/components/Button/stories/examples/ButtonExampleForm/ButtonExampleForm.tsx
  src/components/Button/stories/examples/ButtonExampleIcon/ButtonExampleIcon.tsx
  src/components/Button/stories/examples/ButtonExampleLoading/ButtonExampleLoading.tsx
  src/components/Button/stories/examples/ButtonExampleName/ButtonExampleName.tsx
  src/components/Button/stories/examples/ButtonExampleSize/ButtonExampleSize.tsx
  src/components/Button/stories/examples/ButtonExampleView/ButtonExampleView.tsx
  src/uiKit/components/DocsDecorator/DocsDecorator.css
  src/uiKit/components/DocsDecorator/DocsDecorator.tsx
  yarn.lock
Labels: documentation, feature

#260 feat(Icons): add IconDisconnection and IconRestart
  src/fileIcons/FileIcon/stories/FileIcons.stories.tsx
  src/icons/Icon/stories/Icons.stories.tsx
  src/icons/IconDisconnection/IconDisconnection.tsx
  src/icons/IconDisconnection/IconDisconnection_size_m.svg
  src/icons/IconDisconnection/IconDisconnection_size_m.tsx
  src/icons/IconDisconnection/IconDisconnection_size_s.svg
  src/icons/IconDisconnection/IconDisconnection_size_s.tsx
  src/icons/IconDisconnection/IconDisconnection_size_xs.svg
  src/icons/IconDisconnection/IconDisconnection_size_xs.tsx
  src/icons/IconRestart/IconRestart.tsx
  src/icons/IconRestart/IconRestart_size_m.svg
  src/icons/IconRestart/IconRestart_size_m.tsx
  src/icons/IconRestart/IconRestart_size_s.svg
  src/icons/IconRestart/IconRestart_size_s.tsx
  src/icons/IconRestart/IconRestart_size_xs.svg
  src/icons/IconRestart/IconRestart_size_xs.tsx
Labels: feature

#281 Feature/switch add S size
  src/components/Switch/Switch.css
  src/components/Switch/Switch.tsx
  src/components/Switch/__stories__/Switch.stories.tsx
Labels: feature

#278 feat(Table): add Table component
  src/components/Table/Cell/TableCell.css
  src/components/Table/Cell/TableCell.tsx
  src/components/Table/FilterTooltip/TableFilterTooltip.css
  src/components/Table/FilterTooltip/TableFilterTooltip.tsx
  src/components/Table/Resizer/TableResizer.css
  src/components/Table/Resizer/TableResizer.tsx
  src/components/Table/SelectedOption/TableSelectedOption.css
  src/components/Table/SelectedOption/TableSelectedOption.tsx
  src/components/Table/SelectedOptionsList/TableSelectedOptionsList.css
  src/components/Table/SelectedOptionsList/TableSelectedOptionsList.tsx
  src/components/Table/Table.css
  src/components/Table/Table.tsx
  src/components/Table/__mock__/data.mock.tsx
  src/components/Table/__stories__/Table.mdx
  src/components/Table/__stories__/Table.stories.css
  src/components/Table/__stories__/Table.stories.tsx
  src/components/Table/__tests__/filtering.test.ts
  src/components/Table/__tests__/helpers.test.ts
  src/components/Table/filtering.ts
  src/components/Table/helpers.ts
  src/utils/__tests__/array.test.ts
  src/utils/array.ts
  src/utils/type-guards.ts
Labels: feature
