Repository consta-design-system/uikit, pull requests merged in 2020-12, with the labels that each got.

#641 docs(Sidebar): add docs for Sidebar
  src/components/Sidebar/Sidebar.css
  src/components/Sidebar/__stories__/Sidebar.mdx
  src/components/Sidebar/__stories__/examples/SidebarExample/SidebarExample.css
  src/components/Sidebar/__stories__/examples/SidebarExample/SidebarExample.tsx
Labels: documentation

#644 Tooltip/add statuses
  src/components/Tooltip/Tooltip.css
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/__stories__/Tooltip.mdx
  src/components/Tooltip/__stories__/Tooltip.stories.tsx
Labels: feature

#672 fix(MultiCombobox): fixed click on valueTag
  src/components/MultiCombobox/MultiCombobox.tsx
  src/components/SelectComponents/Select.css
Labels: bug, 🔥🔥🔥 priority

#679 fix(Docs): update line-height for Headings
  src/uiKit/components/DocsDecorator/DocsDecorator.css
Labels: bug, 🔥🔥 priority

#705 bug(Header): изменение цветов ссылок в меню
  src/components/Header/Menu/HeaderMenu.css
Labels: bug

#703 feat(CheckboxGroup): new component
  src/components/CheckboxGroup/CheckboxGroup.css
  src/components/CheckboxGroup/CheckboxGroup.tsx
  src/components/CheckboxGroup/__stories__/CheckboxGroup.mdx
  src/components/CheckboxGroup/__stories__/CheckboxGroup.stories.tsx
  src/components/CheckboxGroup/__tests__/CheckboxGroup.test.tsx
Labels: feature, 🔥🔥 priority

#710 feat:(storyBook) added id for stories
  builder/templates/Icons.stories.tsx.template
  src/components/Attach/__stories__/Attach.stories.tsx
  src/components/Avatar/__stories__/Avatar.stories.tsx
  src/components/Badge/__stories__/Badge.stories.tsx
  src/components/BasicSelect/__stories__/BasicSelect.stories.tsx
  src/components/Button/__stories__/Button.stories.tsx
  src/components/Checkbox/__stories__/Checkbox.stories.tsx
  src/components/CheckboxGroup/__stories__/CheckboxGroup.stories.tsx
  src/components/ChoiceGroup/__stories__/ChoiceGroup.stories.tsx
  src/components/Combobox/__stories__/Combobox.stories.tsx
  src/components/File/__stories__/File.stories.tsx
  src/components/FileField/__stories__/FileField.stories.tsx
  src/components/Header/__stories__/Header.stories.tsx
  src/components/Informer/__stories__/Informer.stories.tsx
  src/components/Loader/__stories__/Loader.stories.tsx
  src/components/Modal/__stories__/Modal.stories.tsx
  src/components/MultiCombobox/__stories__/MultiCombobox.stories.tsx
  src/components/Pagination/__stories__/Pagination.stories.tsx
  src/components/Popover/__stories__/Popover.stories.tsx
  src/components/ProgressSpin/__stories__/ProgressSpin.stories.tsx
  src/components/Radio/__stories__/Radio.stories.tsx
  src/components/RadioGroup/__stories__/RadioGroup.stories.tsx
  src/components/Sidebar/__stories__/Sidebar.stories.tsx
  src/components/SnackBar/__stories__/SnackBar.stories.tsx
  src/components/Steps/__stories__/Steps.stories.tsx
  src/components/Switch/__stories__/Switch.stories.tsx
  src/components/Table/__stories__/Table.stories.tsx
  src/components/Tabs/__stories__/Tabs.stories.tsx
  src/components/Tag/__stories__/Tag.stories.tsx
  src/components/Text/__stories__/Text.stories.tsx
  src/components/TextField/__stories__/TextField.stories.tsx
  src/components/Theme/__stories__/Theme.stories.tsx
  src/components/Timer/__stories__/Timer.stories.tsx
  src/components/Tooltip/__stories__/Tooltip.stories.tsx
  src/components/User/__stories__/User.stories.tsx
  src/icons/Icon/__stories__/Icons.stories.tsx
  src/utils/storybook.tsx
Labels: 🔥🔥🔥 priority

#656 feat(Responses): add new component
  builder/build.js
  builder/helpers.js
  builder/preBuild.js
  builder/templates/ResponsesImage.tsx.template
  src/components/Responses/Responses.css
  src/components/Responses/Responses.tsx
  src/components/Responses/__stories__/Responses.mdx
  src/components/Responses/__stories__/Responses.stories.tsx
  src/components/Responses/createResponses.tsx
  src/components/Responses403/Responses403.tsx
  src/components/Responses404/Responses404.tsx
  src/components/Responses500/Responses500.tsx
  src/components/Responses503/Responses503.tsx
  src/components/ResponsesConnectionError/ResponsesConnectionError.tsx
  src/components/ResponsesDeleted/ResponsesDeleted.tsx
  src/components/ResponsesEmptyBox/ResponsesEmptyBox.tsx
  src/components/ResponsesEmptyPockets/ResponsesEmptyPockets.tsx
  src/components/ResponsesNothingFound/ResponsesNothingFound.tsx
  src/components/ResponsesSuccess/ResponsesSuccess.tsx
  src/responsesImages/ResponsesImage/ResponsesImage.css
  src/responsesImages/ResponsesImage/ResponsesImage.tsx
  src/responsesImages/ResponsesImage403/ResponsesImage403.svg
  src/responsesImages/ResponsesImage403/ResponsesImage403.tsx
  src/responsesImages/ResponsesImage403/ResponsesImage403Svg.tsx
  src/responsesImages/ResponsesImage404/ResponsesImage404.svg
  src/responsesImages/ResponsesImage404/ResponsesImage404.tsx
  src/responsesImages/ResponsesImage404/ResponsesImage404Svg.tsx
  src/responsesImages/ResponsesImage500/ResponsesImage500.svg
  src/responsesImages/ResponsesImage500/ResponsesImage500.tsx
  src/responsesImages/ResponsesImage500/ResponsesImage500Svg.tsx
  src/responsesImages/ResponsesImage503/ResponsesImage503.svg
  src/responsesImages/ResponsesImage503/ResponsesImage503.tsx
  src/responsesImages/ResponsesImage503/ResponsesImage503Svg.tsx
  src/responsesImages/ResponsesImageConnectionError/ResponsesImageConnectionError.svg
  src/responsesImages/ResponsesImageConnectionError/ResponsesImageConnectionError.tsx
  src/responsesImages/ResponsesImageConnectionError/ResponsesImageConnectionErrorSvg.tsx
  src/responsesImages/ResponsesImageDeleted/ResponsesImageDeleted.svg
  src/responsesImages/ResponsesImageDeleted/ResponsesImageDeleted.tsx
  src/responsesImages/ResponsesImageDeleted/ResponsesImageDeletedSvg.tsx
  src/responsesImages/ResponsesImageEmptyBox/ResponsesImageEmptyBox.svg
  src/responsesImages/ResponsesImageEmptyBox/ResponsesImageEmptyBox.tsx
  src/responsesImages/ResponsesImageEmptyBox/ResponsesImageEmptyBoxSvg.tsx
  src/responsesImages/ResponsesImageEmptyPockets/ResponsesImageEmptyPockets.svg
  src/responsesImages/ResponsesImageEmptyPockets/ResponsesImageEmptyPockets.tsx
  src/responsesImages/ResponsesImageEmptyPockets/ResponsesImageEmptyPocketsSvg.tsx
  src/responsesImages/ResponsesImageNothingFound/ResponsesImageNothingFound.svg
  src/responsesImages/ResponsesImageNothingFound/ResponsesImageNothingFound.tsx
  src/responsesImages/ResponsesImageNothingFound/ResponsesImageNothingFoundSvg.tsx
  src/responsesImages/ResponsesImageSuccess/ResponsesImageSuccess.svg
  src/responsesImages/ResponsesImageSuccess/ResponsesImageSuccess.tsx
  src/responsesImages/ResponsesImageSuccess/ResponsesImageSuccessSvg.tsx
  src/responsesImages/createResponsesImage/createResponsesImage.tsx
Labels: docs, feature

#717 feat: (MultiCombobox) fixed getGroupOptions types
  src/components/MultiCombobox/MultiCombobox.tsx
  src/components/MultiCombobox/__stories__/MultiCombobox.stories.tsx
Labels: 🔥🔥🔥 priority

#639 docs(MultiCombobox): add docs for MultiCombobox
  src/components/MultiCombobox/__stories__/MultiCombobox.mdx
  src/components/MultiCombobox/__stories__/examples/MultiComboboxExample/MultiComboboxExample.tsx
  src/components/MultiCombobox/__stories__/examples/MultiComboboxExampleCreate/MultiComboboxExampleCreate.tsx
  src/components/MultiCombobox/__stories__/examples/MultiComboboxExampleGroup/MultiComboboxExampleGroup.tsx
Labels: docs

#723 Sidebar/fix radius
  src/components/Sidebar/Sidebar.css
Labels: bug

#730 docs(sidebar): fix position bottom example
  src/components/Sidebar/__stories__/examples/SidebarExample/SidebarExample.tsx
Labels: docs

#736 Icons/add new pack
  src/components/Header/__stories__/examples/HeaderWithLogoExample/HeaderWithLogoExample.tsx
  src/components/ProgressSpin/ProgressSpin.tsx
  src/fileIcons/FileIconExe/FileIconExe_size_s.svg
  src/fileIcons/FileIconExe/FileIconExe_size_s.tsx
  src/icons/Icon/__stories__/Icons.stories.tsx
  src/icons/IconDraggable/IconDraggable.tsx
  src/icons/IconDraggable/IconDraggable_size_m.svg
  src/icons/IconDraggable/IconDraggable_size_m.tsx
  src/icons/IconDraggable/IconDraggable_size_s.svg
  src/icons/IconDraggable/IconDraggable_size_s.tsx
  src/icons/IconDraggable/IconDraggable_size_xs.svg
  src/icons/IconDraggable/IconDraggable_size_xs.tsx
  src/icons/IconExit/IconExit_size_m.svg
  src/icons/IconExit/IconExit_size_s.svg
  src/icons/IconExit/IconExit_size_xs.svg
  src/icons/IconInfo/IconInfo_size_m.svg
  src/icons/IconInfo/IconInfo_size_s.svg
  src/icons/IconInfo/IconInfo_size_xs.svg
  src/icons/IconIpad/IconIpad_size_m.svg
  src/icons/IconIpad/IconIpad_size_s.svg
  src/icons/IconIpad/IconIpad_size_xs.svg
  src/icons/IconLaptop/IconLaptop_size_m.svg
  src/icons/IconLaptop/IconLaptop_size_s.svg
  src/icons/IconLaptop/IconLaptop_size_xs.svg
  src/icons/IconLightningBolt/IconLightningBolt.tsx
  src/icons/IconLightningBolt/IconLightningBolt_size_m.svg
  src/icons/IconLightningBolt/IconLightningBolt_size_m.tsx
  src/icons/IconLightningBolt/IconLightningBolt_size_s.svg
  src/icons/IconLightningBolt/IconLightningBolt_size_s.tsx
  src/icons/IconLightningBolt/IconLightningBolt_size_xs.svg
  src/icons/IconLightningBolt/IconLightningBolt_size_xs.tsx
  src/icons/IconLogicalElement/IconLogicalElement.tsx
  src/icons/IconLogicalElement/IconLogicalElement_size_m.svg
  src/icons/IconLogicalElement/IconLogicalElement_size_m.tsx
  src/icons/IconLogicalElement/IconLogicalElement_size_s.svg
  src/icons/IconLogicalElement/IconLogicalElement_size_s.tsx
  src/icons/IconLogicalElement/IconLogicalElement_size_xs.svg
  src/icons/IconLogicalElement/IconLogicalElement_size_xs.tsx
  src/icons/IconSmile/IconSmile_size_m.svg
  src/icons/IconSmile/IconSmile_size_s.svg
  src/icons/IconSmile/IconSmile_size_xs.svg
  src/icons/IconSun/IconSun_size_m.svg
  src/icons/IconSun/IconSun_size_m.tsx
  src/icons/IconUnlock/IconUnlock.tsx
  src/icons/IconUnlock/IconUnlock_size_m.svg
  src/icons/IconUnlock/IconUnlock_size_m.tsx
  src/icons/IconUnlock/IconUnlock_size_s.svg
  src/icons/IconUnlock/IconUnlock_size_s.tsx
  src/icons/IconUnlock/IconUnlock_size_xs.svg
  src/icons/IconUnlock/IconUnlock_size_xs.tsx
  src/icons/IconUpload/IconUpload.tsx
  src/icons/IconUpload/IconUpload_size_m.svg
  src/icons/IconUpload/IconUpload_size_m.tsx
  src/icons/IconUpload/IconUpload_size_s.svg
  src/icons/IconUpload/IconUpload_size_s.tsx
  src/icons/IconUpload/IconUpload_size_xs.svg
  src/icons/IconUpload/IconUpload_size_xs.tsx
  src/icons/IconWideScreen/IconWideScreen_size_m.svg
  src/icons/IconWideScreen/IconWideScreen_size_s.svg
Labels: feature
