Repository consta-design-system/uikit, pull requests merged in 2020-08, with the labels that each got.

#332 feat(Icons): add new icons MaxWidth and Phone
  src/icons/Icon/__stories__/Icons.stories.tsx
  src/icons/IconMaxWidth/IconMaxWidth.tsx
  src/icons/IconMaxWidth/IconMaxWidth_size_m.svg
  src/icons/IconMaxWidth/IconMaxWidth_size_m.tsx
  src/icons/IconMaxWidth/IconMaxWidth_size_s.svg
  src/icons/IconMaxWidth/IconMaxWidth_size_s.tsx
  src/icons/IconMaxWidth/IconMaxWidth_size_xs.svg
  src/icons/IconMaxWidth/IconMaxWidth_size_xs.tsx
  src/icons/IconPhone/IconPhone.tsx
  src/icons/IconPhone/IconPhone_size_m.svg
  src/icons/IconPhone/IconPhone_size_m.tsx
  src/icons/IconPhone/IconPhone_size_s.svg
  src/icons/IconPhone/IconPhone_size_s.tsx
  src/icons/IconPhone/IconPhone_size_xs.svg
  src/icons/IconPhone/IconPhone_size_xs.tsx
Labels: feature

#339 fix(Docs): fix DocsExample styles
  src/uiKit/components/DocsExample/DocsExample.tsx
Labels: bug, documentation

#341 docs(Button): fix link to example
  src/components/Button/__stories__/Button.mdx
Labels: bug, documentation

#342 docs(file-structure): add docs file structure
  docs/common/developers/commits-style.mdx
  docs/common/developers/contributors.mdx
  docs/common/developers/file-structure/file-structure-components.mdx
  docs/common/developers/file-structure/file-structure.mdx
  docs/common/developers/review.mdx
Labels: documentation

#340 fix(Attach): fix onButtonClick
  src/components/Attach/Attach.css
  src/components/Attach/Attach.tsx
Labels: bug

#289 docs(File): add docs for File
  src/components/File/__stories__/File.mdx
  src/components/File/__stories__/examples/FileExampleLoading/FileExampleLoading.tsx
Labels: documentation

#307 Docs(Avatar): add docs for Avatar
  src/components/Avatar/__stories__/Avatar.mdx
  src/components/Avatar/__stories__/examples/AvatarExampleForm/AvatarExampleForm.tsx
  src/components/Avatar/__stories__/examples/AvatarExampleImage/AvatarExampleImage.tsx
  src/components/Avatar/__stories__/examples/AvatarExampleSize/AvatarExampleSize.tsx
Labels: documentation

#319 Docs/Informer
  src/components/Informer/__stories__/Informer.mdx
  src/components/Informer/__stories__/examples/InformerExampleIcon/InformerExampleIcon.tsx
  src/components/Informer/__stories__/examples/InformerExampleText/InformerExampleText.tsx
  src/components/Informer/__stories__/examples/InformerExampleType/InformerExampleType.tsx
  src/components/Informer/__stories__/examples/InformerExampleView/InformerExampleView.tsx
Labels: documentation

#320 Docs/Loader
  src/components/Loader/__stories__/Loader.mdx
  src/components/Loader/__stories__/examples/LoaderExampleSize/LoaderExampleSize.tsx
Labels: documentation

#300 Docs(Text): edit docs for Text
  src/components/Text/__stories__/Text.mdx
  src/components/Text/__stories__/examples/TextExampleAlign/TextExampleAlign.tsx
  src/components/Text/__stories__/examples/TextExampleDecoration/TextExampleDecoration.tsx
  src/components/Text/__stories__/examples/TextExampleHeadingAndParagraph/TextExampleHeadingAndParagraph.tsx
  src/components/Text/__stories__/examples/TextExampleLabelAndData/TextExampleLabelAndData.tsx
  src/components/Text/__stories__/examples/TextExampleLineheight/TextExampleLineheight.tsx
  src/components/Text/__stories__/examples/TextExampleSpacing/TextExampleSpacing.tsx
  src/components/Text/__stories__/examples/TextExampleStyle/TextExampleStyle.tsx
  src/components/Text/__stories__/examples/TextExampleTransform/TextExampleTransform.tsx
  src/components/Text/__stories__/examples/TextExampleView/TextExampleView.tsx
  src/components/Text/__stories__/examples/TextExampleWeight/TextExampleWeight.tsx
Labels: documentation

#321 Docs/Radio
  src/components/Radio/Radio.tsx
  src/components/Radio/__stories__/Radio.mdx
  src/components/Radio/__stories__/examples/RadioExampleSize/RadioExampleSize.tsx
  src/components/Radio/__stories__/examples/RadioExampleStatus/RadioExampleStatus.tsx
  src/components/Radio/__stories__/examples/RadioExampleUse/RadioExampleUse.tsx
Labels: documentation

#322 Docs/Switch
  src/components/Switch/__stories__/Switch.mdx
  src/components/Switch/__stories__/Switch.stories.tsx
  src/components/Switch/__stories__/examples/SwitchExampleName/SwitchExampleName.tsx
  src/components/Switch/__stories__/examples/SwitchExampleSize/SwitchExampleSize.tsx
  src/components/Switch/__stories__/examples/SwitchExampleStatus/SwitchExampleStatus.tsx
Labels: documentation
