Repository consta-design-system/uikit, pull requests merged in 2021-06, with the labels that each got.

#1252 docs(icons): add docs for new icons
  docs/common/icons/components/InstructionPictures/InstructionPictures.tsx
  docs/common/icons/components/InstructionPictures/images/1-icons-grid.svg
  docs/common/icons/components/InstructionPictures/images/10-finder.png
  docs/common/icons/components/InstructionPictures/images/11-github.png
  docs/common/icons/components/InstructionPictures/images/2-icons-grid.svg
  docs/common/icons/components/InstructionPictures/images/3-icons-grid.svg
  docs/common/icons/components/InstructionPictures/images/4-figma-union.png
  docs/common/icons/components/InstructionPictures/images/5-icons-grid.svg
  docs/common/icons/components/InstructionPictures/images/6-examples.svg
  docs/common/icons/components/InstructionPictures/images/7-figma.png
  docs/common/icons/components/InstructionPictures/images/8-github.png
  docs/common/icons/components/InstructionPictures/images/9-figma.png
  docs/common/icons/icons.stories.mdx
Labels: docs, improvement

#1254 fix(Theme): fix color calculation parameter
  src/components/Theme/_color/Theme_color_gpnDefault.css
Labels: bug

#1247 docs(useChoiceGroup): edit docs
  src/hooks/useChoiceGroup/__stories__/useChoiceGroup.stories.mdx
Labels: docs

#1248 docs(useClickOutside): edit docs
  src/hooks/useClickOutside/__stories__/useClickOutside.stories.mdx
Labels: docs

#1249 docs(UseDebounce): edit docs
  src/hooks/useDebounce/__stories__/examples/UseDebounceExample/UseDebounceExample.tsx
  src/hooks/useDebounce/__stories__/useDebounce.stories.mdx
Labels: docs

#1250 docs(useForkRef): edit docs
  src/hooks/useForkRef/__stories__/useForkRef.stories.mdx
Labels: docs

#1251 docs(useThemeVars): edit docs
  src/hooks/useThemeVars/__stories__/useThemeVars.stories.mdx
Labels: docs

#1288 docs(Text): remove width description
  src/components/Text/__stories__/Text.docs.mdx
Labels: docs

#1287 docs(Informer): add size description in documentation
  src/components/Informer/__stories__/Informer.docs.mdx
  src/components/Informer/__stories__/examples/InformerExampleSize/InformerExampleSize.tsx
Labels: docs

#1302 docs(sla): add sla
  docs/common.d.ts
  docs/common/sla/components/SlaPictures/SlaPictures.tsx
  docs/common/sla/components/SlaPictures/images/sla-scheme.png
  docs/common/sla/sla.stories.mdx
  src/uiKit/components/DocsDecorator/DocsDecorator.css
  src/uiKit/components/Image/Image.css
  src/uiKit/components/Image/Image.tsx
Labels: docs, feature
