Repository consta-design-system/uikit, pull requests merged in 2021-04, with the labels that each got.

#1023 docs(common): add docs about issues
  docs/common/developers/issues.mdx
Labels: docs

#1058 feat(Icon): add new icons
  builder/templates/Icons.stories.tsx.template
  src/icons/Icon/__stories__/Icons.stories.tsx
  src/icons/IconBook/IconBook.tsx
  src/icons/IconBook/IconBook_size_m.svg
  src/icons/IconBook/IconBook_size_m.tsx
  src/icons/IconBook/IconBook_size_s.svg
  src/icons/IconBook/IconBook_size_s.tsx
  src/icons/IconBook/IconBook_size_xs.svg
  src/icons/IconBook/IconBook_size_xs.tsx
  src/icons/IconDataNull/IconDataNull.tsx
  src/icons/IconDataNull/IconDataNull_size_m.svg
  src/icons/IconDataNull/IconDataNull_size_m.tsx
  src/icons/IconDataNull/IconDataNull_size_s.svg
  src/icons/IconDataNull/IconDataNull_size_s.tsx
  src/icons/IconDataNull/IconDataNull_size_xs.svg
  src/icons/IconDataNull/IconDataNull_size_xs.tsx
  src/icons/IconLineAndBarChart/IconLineAndBarChart_size_m.tsx
  src/icons/IconLineAndBarChart/IconLineAndBarChart_size_s.tsx
Labels: feature, improvement

#1053 docs(Header): edit docs
  src/components/Header/__stories__/Header.mdx
  src/components/Header/__stories__/examples/HeaderFullExample/HeaderFullExample.tsx
  src/components/Header/__stories__/examples/HeaderLoginExample/HeaderLoginExample.tsx
  src/components/Header/__stories__/examples/HeaderMinifyLoginExample/HeaderMinifyLoginExample.tsx
  src/components/Header/__stories__/examples/HeaderWithLogoExample/HeaderWithLogoExample.tsx
  src/components/Header/__stories__/examples/HeaderWithoutMenuExample/HeaderWithoutMenuExample.tsx
  src/components/Header/__stories__/examples/HeaderWithoutSearchExample/HeaderWithoutSearchExample.tsx
  src/components/Header/__tests__/HeaderMenu.test.tsx
Labels: docs

#1045 docs(ThemeToggler): update docs
  src/components/ThemeToggler/__stories__/ThemeToggler.mdx
  src/components/ThemeToggler/__stories__/examples/ThemeTogglerExampleSize/ThemeTogglerExampleSize.css
  src/components/ThemeToggler/__stories__/examples/ThemeTogglerExampleSize/ThemeTogglerExampleSize.tsx
Labels: docs

#1034 docs(FileField): edit docs for FileField
  src/components/FileField/__stories__/FileField.mdx
  src/components/FileField/__stories__/examples/FileFieldExampleWithoutRenderProp/FileFieldExampleWithoutRenderProp.tsx
Labels: docs

#1100 fix(components): collapse
  src/components/Collapse/__stories__/Collapse.stories.tsx
Labels: bug

#1098 fix(github): Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: bug
