Repository consta-design-system/uikit, pull requests merged in 2021-11, with the labels that each got.

#1728 fix(Combobox): fix bug with notFoundLabel
  src/hooks/useSelect/useSelect.ts
Labels: bug

#1725 docs(TextField): review docs, add type=number
  src/components/TextField/TextField.tsx
  src/components/TextField/__stories__/TextField.docs.mdx
  src/components/TextField/__stories__/TextField.stories.tsx
  src/components/TextField/__stories__/examples/TextFieldExampleCaption/TextFieldExampleCaption.tsx
  src/components/TextField/__stories__/examples/TextFieldExampleFocus/TextFieldExampleFocus.tsx
  src/components/TextField/__stories__/examples/TextFieldExampleForm/TextFieldExampleForm.tsx
  src/components/TextField/__stories__/examples/TextFieldExampleLabel/TextFieldExampleLabel.tsx
  src/components/TextField/__stories__/examples/TextFieldExampleRequired/TextFieldExampleRequired.tsx
  src/components/TextField/__stories__/examples/TextFieldExampleSize/TextFieldExampleSize.tsx
  src/components/TextField/__stories__/examples/TextFieldExampleStatus/TextFieldExampleStatus.tsx
  src/components/TextField/__stories__/examples/TextFieldExampleType/TextFieldExampleType.tsx
  src/components/TextField/__stories__/examples/TextFieldExampleView/TextFieldExampleView.tsx
Labels: docs

#1759 fix(Select): fix bug with placeholder
  src/components/Select/Select.tsx
Labels: bug, 🔥🔥🔥 priority

#1777 docs(DatePicker): add note about this doc
  src/components/DatePickerCanary/__stories__/DatePicker.docs.mdx
Labels: docs

#1773 docs(common): add components and images to review
  src/components/Attachment/__stories__/Attachment.image.svg
  src/components/ProgressStepBarCanary/__stories__/ProgressStepBar.docs.mdx
  src/components/Tabs/__stories__/Tabs.image.svg
  src/components/Tooltip/__stories__/Tooltip.image.svg
  src/uiKit/components/ComponentsGridWithData/data/data.ts
  src/uiKit/components/ComponentsGridWithData/data/images/AttachmentImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/images/TabsImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/images/TooltipImage.tsx
Labels: docs

#1766 docs(developer): add pages about design and code style
  docs/common/developers/arrangements-for-code-style.stories.mdx
  docs/common/developers/design.stories.mdx
  docs/common/developers/docs.stories.mdx
Labels: docs

#1774 docs(Avatar): add size L to docs
  src/components/Avatar/__stories__/Avatar.docs.mdx
  src/components/Avatar/__stories__/examples/AvatarExampleSize/AvatarExampleSize.tsx
Labels: docs

#1778 docs(DateTime): edit docs, fix format
  src/components/DateTimeCanary/__stories__/DateTime.docs.mdx
Labels: docs

#1776 feat(MixSpace): add new mixin and documentation for him
  src/mixs/MixSpace/MixSpace.css
  src/mixs/MixSpace/MixSpace.tsx
  src/mixs/MixSpace/__stories__/MixSpace.stories.mdx
Labels: feature

#1793 fix(useSelect): fix bug with notFoundLabel
  src/hooks/useSelect/useSelect.ts
Labels: bug

#1792 feat(SnackBar): add adaptivity for SnackBar
  src/components/SnackBar/SnackBar.css
  src/components/SnackBar/__stories__/SnackBar.stories.css
Labels: feature

#1798 refactor(getSizeByMap): rename from getSizeByMap to getByMap
  src/components/Breadcrumbs/Breadcrumbs.tsx
  src/components/Button/Button.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/__stories__/Calendar.stories.tsx
  src/components/ChoiceGroup/ChoiceGroup.tsx
  src/components/Collapse/Collapse.tsx
  src/components/Collapse/__stories__/Collapse.stories.tsx
  src/components/CollapseGroup/__tests__/CollapseGroup.test.tsx
  src/components/ContextMenu/ContextMenuGroupHeader/ContextMenuGroupHeader.tsx
  src/components/DatePickerCanary/DatePickerFieldTypeDateRange/DatePickerFieldTypeDateRange.tsx
  src/components/DatePickerCanary/__stories__/DatePicker.stories.tsx
  src/components/DateTimeCanary/DateTimeCanary.tsx
  src/components/DateTimeCanary/__stories__/DateTime.stories.tsx
  src/components/ProgressSpin/ProgressSpin.tsx
  src/components/ProgressStepBarCanary/ProgressStepBarLine/ProgressStepBarLine.tsx
  src/components/SelectComponents/SelectItem/SelectItem.tsx
  src/components/SelectComponentsDeprecated/SelectItem/SelectItem.tsx
  src/components/Steps/StepsStep/StepsStep.tsx
  src/components/Tabs/Tab/TabsTab.tsx
  src/components/TagBase/TagBase.tsx
  src/components/TextField/TextField.tsx
  src/components/ThemeToggler/ThemeToggler.tsx
  src/components/User/User.tsx
  src/utils/getByMap.test.tsx
  src/utils/getByMap.tsx
Labels: feature, 🔥🔥🔥 priority

#1808 fix(Theme): fix system colors
  src/components/Theme/_color/Theme_color_gpnDark.css
  src/components/Theme/_color/Theme_color_gpnDefault.css
  src/components/Theme/_color/Theme_color_gpnDisplay.css
Labels: bug, 🔥🔥 priority

#1812 docs(MixSpace): edit docs, add examples
  src/mixs/MixSpace/__stories__/MixSpace.stories.mdx
  src/mixs/MixSpace/__stories__/examples/MixSpaceExample/MixSpaceExample.tsx
Labels: docs

#1814 docs(review): add component images, fix misprints
  src/components/Attachment/__stories__/Attachment.docs.mdx
  src/components/Avatar/__stories__/Avatar.image.svg
  src/components/Badge/__stories__/Badge.image.svg
  src/components/Collapse/__stories__/Collapse.image.svg
  src/components/CollapseGroup/__stories__/CollapseGroup.image.svg
  src/components/Combobox/__stories__/Combobox.image.svg
  src/components/DatePickerCanary/__stories__/DatePicker.image.svg
  src/components/DragNDropField/__stories__/DragNDropField.image.svg
  src/components/Loader/__stories__/Loader.image.svg
  src/components/Modal/__stories__/Modal.image.svg
  src/components/ProgressSpin/__stories__/ProgressSpin.docs.mdx
  src/components/Responses/__stories__/Responses.image.svg
  src/components/Select/__stories__/Select.image.svg
  src/components/Sidebar/__stories__/Sidebar.image.svg
  src/components/SnackBar/__stories__/SnackBar.image.svg
  src/components/Switch/__stories__/Switch.docs.mdx
  src/components/Tag/__stories__/Tag.docs.mdx
  src/components/Tag/__stories__/Tag.image.svg
  src/components/Theme/__stories__/Theme.image.svg
  src/components/ThemeToggler/__stories__/ThemeToggler.image.svg
  src/components/Timer/__stories__/Timer.image.svg
  src/components/User/__stories__/User.docs.mdx
  src/components/UserSelect/__stories__/UserSelect.docs.mdx
  src/components/UserSelect/__stories__/UserSelect.image.svg
  src/icons/Icon/__stories__/Icon.image.svg
  src/uiKit/components/ComponentsGridWithData/data/data.ts
  src/uiKit/components/ComponentsGridWithData/data/images/AvatarImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/images/BadgeImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/images/CollapseGroupImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/images/CollapseImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/images/ComboboxImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/images/DatePickerImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/images/DragNDropFieldImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/images/LoaderImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/images/ModalImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/images/ResponsesImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/images/SelectImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/images/SidebarImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/images/SnackBarImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/images/TagImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/images/ThemeImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/images/ThemeTogglerImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/images/TimerImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/images/UserSelectImage.tsx
Labels: docs
