Repository consta-design-system/uikit, pull requests merged in 2022-10, with the labels that each got.

#2667 feat(Table): add new props to table props and table row for expands rows
  src/components/Table/RowsCollapse/TableRowsCollapse.tsx
  src/components/Table/Table.tsx
  src/components/Table/__stand__/Table.dev.stand.mdx
  src/components/Table/__stand__/examples/TableExampleExpandable/TableExampleExpandable.tsx
Labels: docs, feature

#2702 docs(File): add block for extensions with icon
  src/components/File/__stand__/File.dev.stand.mdx
Labels: docs

#2704 fix(SelectItem): fix height of item with empty row
  src/components/SelectComponents/SelectItem/SelectItem.css
Labels: bug

#2705 docs(Layout): fix border on layout examples
  src/components/Layout/__stand__/Layout.variants.css
  src/components/Layout/__stand__/examples/LayoutExampleAnchor/LayoutExampleAnchor.css
  src/components/Layout/__stand__/examples/LayoutExampleBasic/LayoutExampleBasic.css
  src/components/Layout/__stand__/examples/LayoutExampleDirection/LayoutExampleDirection.css
  src/components/Layout/__stand__/examples/LayoutExampleDirection/LayoutExampleDirection.tsx
  src/components/Layout/__stand__/examples/LayoutExampleFixed/LayoutExampleFixed.css
  src/components/Layout/__stand__/examples/LayoutExampleRowFixed/LayoutExampleRowFixed.css
Labels: docs

#2693 Feat/auto complete
  src/components/AutoCompleteCanary/AutoCompleteCanary.tsx
  src/components/AutoCompleteCanary/__mocks__/data.mock.ts
  src/components/AutoCompleteCanary/__stand__/AutoComplete.dev.stand.mdx
  src/components/AutoCompleteCanary/__stand__/AutoComplete.stand.mdx
  src/components/AutoCompleteCanary/__stand__/AutoComplete.stand.tsx
  src/components/AutoCompleteCanary/__stand__/AutoComplete.variants.css
  src/components/AutoCompleteCanary/__stand__/AutoComplete.variants.tsx
  src/components/AutoCompleteCanary/__stand__/examples/AutoCompleteExampleBasic/AutoCompleteExampleBasic.tsx
  src/components/AutoCompleteCanary/__stand__/examples/AutoCompleteExampleDisabled/AutoCompleteExampleDisabled.tsx
  src/components/AutoCompleteCanary/__stand__/examples/AutoCompleteExampleForm/AutoCompleteExampleForm.tsx
  src/components/AutoCompleteCanary/__stand__/examples/AutoCompleteExampleGroups/AutoCompleteExampleGroups.tsx
  src/components/AutoCompleteCanary/__stand__/examples/AutoCompleteExampleItems/AutoCompleteExampleItems.tsx
  src/components/AutoCompleteCanary/__stand__/examples/AutoCompleteExampleLabel/AutoCompleteExampleLabel.tsx
  src/components/AutoCompleteCanary/__stand__/examples/AutoCompleteExamplePlaceholder/AutoCompleteExamplePlaceholder.tsx
  src/components/AutoCompleteCanary/__stand__/examples/AutoCompleteExampleRenderItem/AutoCompleteExampleRenderItem.css
  src/components/AutoCompleteCanary/__stand__/examples/AutoCompleteExampleRenderItem/AutoCompleteExampleRenderItem.tsx
  src/components/AutoCompleteCanary/__stand__/examples/AutoCompleteExampleSize/AutoCompleteExampleSize.tsx
  src/components/AutoCompleteCanary/__stand__/examples/AutoCompleteExampleStatus/AutoCompleteExampleStatus.tsx
  src/components/AutoCompleteCanary/__stand__/examples/AutoCompleteExampleType/AutoCompleteExampleType.tsx
  src/components/AutoCompleteCanary/__stand__/examples/AutoCompleteExampleView/AutoCompleteExampleView.tsx
  src/components/AutoCompleteCanary/helpers.ts
  src/components/AutoCompleteCanary/types.ts
  src/components/AutoCompleteCanary/useAutoComplete.ts
  src/hooks/useSelect/useSelect.ts
  src/utils/bem.ts
Labels: feature

#2710 docs: table comparison
  src/docs/tableComparison/components/AboutData/AboutData.css
  src/docs/tableComparison/components/AboutData/AboutData.tsx
  src/docs/tableComparison/tableComparison.stand.mdx
  src/docs/tableComparison/tableComparison.stand.tsx
Labels: docs
