Repository consta-design-system/uikit, pull requests merged in 2022-05, with the labels that each got.

#2261 docs(Snackbar): add adaptive section
  src/components/SnackBar/__stories__/SnackBar.docs.mdx
  src/components/SnackBar/__stories__/examples/SnackBarExampleAdaptive/SnackBarExampleAdaptive.tsx
Labels: docs

#2266 docs(Steps): add adaptive
  src/components/Steps/__stories__/Steps.docs.mdx
  src/components/Steps/__stories__/examples/ExampleStepsAdaptive/ExampleStepsAdaptive.tsx
Labels: docs

#2267 Fix/combobox
  src/components/Combobox/Combobox.tsx
  src/components/SelectComponents/Select.css
  src/components/SelectComponents/SelectContainer/SelectContainer.tsx
  src/components/UserSelect/UserSelect.tsx
Labels: bug

#2275 docs(Header): fix typo in doc
  src/components/Header/__stories__/Header.docs.mdx
Labels: docs

#2278 docs(Table): add adaptive section
  src/components/Table/__stories__/Table.docs.mdx
  src/components/Table/__stories__/examples/TableExampleAdaptive/TableExampleAdaptive.tsx
Labels: docs

#2289 docs(review): add MixPlot and agGridAdapter
  src/uiKit/components/ComponentsGridWithData/data/additionalData.ts
  src/uiKit/components/ComponentsGridWithData/data/data.ts
Labels: docs

#2298 fix(Slider): fix detecting of active line
  src/components/SliderCanary/useSliderStationing.ts
Labels: bug

#2309 feat(Tabs): change getters to optional parametrs
  src/components/TabsCanary/FitModeDropdownWrapper/TabsFitModeDropdownWrapper.css
  src/components/TabsCanary/FitModeDropdownWrapper/TabsFitModeDropdownWrapper.tsx
  src/components/TabsCanary/FitModeDropdownWrapper/__tests__/useFittingItems.ts
  src/components/TabsCanary/FitModeDropdownWrapper/useFittingItems.ts
  src/components/TabsCanary/FitModeScrollWrapper/TabsFitModeScrollWrapper.css
  src/components/TabsCanary/FitModeScrollWrapper/TabsFitModeScrollWrapper.tsx
  src/components/TabsCanary/FitModeScrollWrapper/__test__/helpers.test.ts
  src/components/TabsCanary/Line/TabsLine.css
  src/components/TabsCanary/Line/TabsLine.tsx
  src/components/TabsCanary/MoreItems/TabsMoreItems.css
  src/components/TabsCanary/MoreItems/TabsMoreItems.tsx
  src/components/TabsCanary/Tab/TabsTab.css
  src/components/TabsCanary/Tab/TabsTab.tsx
  src/components/TabsCanary/Tabs.css
  src/components/TabsCanary/TabsCanary.tsx
  src/components/TabsCanary/__stories__/Tabs.docs.mdx
  src/components/TabsCanary/__stories__/Tabs.image.svg
  src/components/TabsCanary/__stories__/Tabs.stories.tsx
  src/components/TabsCanary/__stories__/examples/TabsExample/TabsExample.tsx
  src/components/TabsCanary/__stories__/examples/TabsExampleFitModeDropdown/TabsExampleFitModeDropdown.tsx
  src/components/TabsCanary/__stories__/examples/TabsExampleFitModeScroll/TabsExampleFitModeScroll.tsx
  src/components/TabsCanary/__stories__/examples/TabsExampleIcon/TabsExampleIcon.tsx
  src/components/TabsCanary/__stories__/examples/TabsExampleLinePosition/TabsExampleLinePosition.tsx
  src/components/TabsCanary/__stories__/examples/TabsExampleRenderItem/TabsExampleRenderItem.tsx
  src/components/TabsCanary/__stories__/examples/TabsExampleSize/TabsExampleSize.tsx
  src/components/TabsCanary/__stories__/examples/TabsExampleView/TabsExampleView.tsx
  src/components/TabsCanary/__tests__/Tabs.test.tsx
  src/components/TabsCanary/helpers.tsx
  src/components/TabsCanary/types.ts
Labels: feature

#2313 feat(RadioGroup): change getters to optional
  src/components/RadioGroupCanary/RadioGroup.css
  src/components/RadioGroupCanary/RadioGroupCannary.tsx
  src/components/RadioGroupCanary/__mocks__/data.mock.ts
  src/components/RadioGroupCanary/__stories__/RadioGroup.docs.mdx
  src/components/RadioGroupCanary/__stories__/RadioGroup.image.svg
  src/components/RadioGroupCanary/__stories__/RadioGroup.stories.tsx
  src/components/RadioGroupCanary/__stories__/examples/RadioGroupExampleAlign/RadioGroupExampleAlign.tsx
  src/components/RadioGroupCanary/__stories__/examples/RadioGroupExampleDisabled/RadioGroupExampleDisabled.tsx
  src/components/RadioGroupCanary/__stories__/examples/RadioGroupExampleSize/RadioGroupExampleSize.tsx
  src/components/RadioGroupCanary/__stories__/examples/RadioGroupExampleUse/RadioGroupExampleUse.tsx
  src/components/RadioGroupCanary/__stories__/examples/RadioGroupExampleView/RadioGroupExampleView.tsx
  src/components/RadioGroupCanary/__tests__/RadioGroup.test.tsx
  src/components/RadioGroupCanary/helper.ts
  src/components/RadioGroupCanary/types.ts
Labels: feature
