Repository consta-design-system/uikit, pull requests merged in 2022-03, with the labels that each got.

#2080 feat(Popover): rewrite offset type
  src/components/ContextMenu/__stories__/ContextMenu.docs.mdx
  src/components/ContextMenu/helpers.tsx
  src/components/Popover/Popover.css
  src/components/Popover/Popover.tsx
  src/components/Popover/__stories__/Popover.docs.mdx
  src/components/Popover/__stories__/Popover.stories.tsx
  src/components/Popover/helpers.ts
Labels: feature

#2051 Fix/table
  src/components/Table/Table.css
  src/components/Table/Table.tsx
  src/components/Table/__tests__/helpers.test.ts
  src/components/Table/helpers.ts
Labels: bug

#2113 fix(Select): fix width
  src/components/SelectComponents/SelectDropdown/SelectDropdown.css
Labels: bug

#2104 docs(principles): add doc
  docs/common/about/principles.stories.mdx
Labels: docs

#2105 feat(ThemeToggler): rewrite examples, doc and component with getters
  src/components/ThemeToggler/ThemeToggler.tsx
  src/components/ThemeToggler/__mocks__/data.mock.ts
  src/components/ThemeToggler/__stories__/ThemeToggler.docs.mdx
  src/components/ThemeToggler/__stories__/ThemeToggler.stories.tsx
  src/components/ThemeToggler/__stories__/examples/ThemeTogglerExampleDefault/ThemeTogglerExampleDefault.tsx
  src/components/ThemeToggler/__stories__/examples/ThemeTogglerExampleGetters/ThemeTogglerExampleGetters.tsx
  src/components/ThemeToggler/__stories__/examples/ThemeTogglerExampleQuantity/ThemeTogglerExampleQuantity.tsx
  src/components/ThemeToggler/__stories__/examples/ThemeTogglerExampleSize/ThemeTogglerExampleSize.tsx
  src/components/ThemeToggler/__tests__/ThemeToggler.test.tsx
  src/components/ThemeToggler/helpers.ts
  src/components/ThemeToggler/types.ts
Labels: feature

#2129 feat(MixPopoverArrow): add new mixin
  src/components/Tooltip/Tooltip.css
  src/components/Tooltip/Tooltip.tsx
  src/mixs/MixPopoverArrow/MixPopoverArrow.css
  src/mixs/MixPopoverArrow/MixPopoverArrow.tsx
  src/mixs/MixPopoverArrow/__stories__/MixPopoverArrow.stories.mdx
  src/mixs/MixPopoverArrow/__stories__/examples/MixPopoverArrowExample/MixPopoverArrowExample.css
  src/mixs/MixPopoverArrow/__stories__/examples/MixPopoverArrowExample/MixPopoverArrowExample.tsx
Labels: feature

#2079 Feat/context menu canary
  src/components/ContextMenu/__stories__/ContextMenu.docs.mdx
  src/components/ContextMenu/__stories__/ContextMenu.stories.tsx
  src/components/ContextMenuCanary/ContextMenu.css
  src/components/ContextMenuCanary/ContextMenuCanary.tsx
  src/components/ContextMenuCanary/ContextMenuItem/ContextMenuItem.css
  src/components/ContextMenuCanary/ContextMenuItem/ContextMenuItem.tsx
  src/components/ContextMenuCanary/ContextMenuLevel/ContextMenuLevel.css
  src/components/ContextMenuCanary/ContextMenuLevel/ContextMenuLevel.tsx
  src/components/ContextMenuCanary/ContextMenuLevels/ContextMenuLevels.tsx
  src/components/ContextMenuCanary/__mocks__/mock.data.ts
  src/components/ContextMenuCanary/__stories__/ContextMenu.docs.mdx
  src/components/ContextMenuCanary/__stories__/ContextMenu.image.svg
  src/components/ContextMenuCanary/__stories__/ContextMenu.stories.tsx
  src/components/ContextMenuCanary/__stories__/examples/ContextMenuExampleDefault/ContextMenuExampleDefault.tsx
  src/components/ContextMenuCanary/__stories__/examples/ContextMenuExampleDisabled/ContextMenuExampleDisabled.tsx
  src/components/ContextMenuCanary/__stories__/examples/ContextMenuExampleGroups/ContextMenuExampleGroups.tsx
  src/components/ContextMenuCanary/__stories__/examples/ContextMenuExampleIcon/ContextMenuExampleIcon.tsx
  src/components/ContextMenuCanary/__stories__/examples/ContextMenuExampleLabel/ContextMenuExampleLabel.tsx
  src/components/ContextMenuCanary/__stories__/examples/ContextMenuExampleOutsideClick/ContextMenuExampleOutsideClick.tsx
  src/components/ContextMenuCanary/__stories__/examples/ContextMenuExampleSide/ContextMenuExampleSide.tsx
  src/components/ContextMenuCanary/__stories__/examples/ContextMenuExampleSize/ContextMenuExampleSize.tsx
  src/components/ContextMenuCanary/__stories__/examples/ContextMenuExampleStatus/ContextMenuExampleStatus.tsx
  src/components/ContextMenuCanary/__stories__/examples/ContextMenuExampleSubMenu/ContextMenuExampleSubMenu.tsx
  src/components/ContextMenuCanary/helper.ts
  src/components/ContextMenuCanary/types.ts
  src/uiKit/components/ComponentsGridWithData/data/data.ts
Labels: feature

#2137 feat(EventInterceptor): connect other components to EventInterceptor
  src/components/Calendar/Calendar.tsx
  src/components/Collapse/Collapse.tsx
  src/components/Combobox/Combobox.tsx
  src/components/ContextMenuCanary/ContextMenuCanary.tsx
  src/components/DatePickerCanary/DatePickerCanary.tsx
  src/components/DateTimeCanary/DateTimeCanary.tsx
  src/components/DragNDropField/DragNDropField.tsx
  src/components/FileField/FileField.tsx
  src/components/Pagination/Pagination.tsx
  src/components/ProgressStepBarCanary/ProgressStepBarCanary.tsx
  src/components/Radio/Radio.tsx
  src/components/SliderCanary/SliderCanary.tsx
  src/components/Switch/Switch.tsx
  src/components/ThemeToggler/ThemeToggler.tsx
  src/components/UserSelect/UserSelect.tsx
Labels: feature

#2143 docs(common): add images to review, components, repos and figma
  docs/common/figma/components/FigmaData/FigmaData.tsx
  docs/common/repos/components/ReposData/ReposData.tsx
  src/uiKit/components/ComponentsGridWithData/data/additionalData.ts
  src/uiKit/components/ComponentsGridWithData/data/imagesForAdditionalData/GpnResponsesImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/imagesForAdditionalData/HeaderUmdImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/imagesForAdditionalData/RcTableAdapterImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/imagesForAdditionalData/RcTreeAdapterImage.tsx
Labels: docs

#2146 feat(Icons): add new icons for social
  src/icons/Icon/__stories__/Icons.stories.tsx
  src/icons/IconFacebook/IconFacebook.tsx
  src/icons/IconFacebook/IconFacebook_size_m.svg
  src/icons/IconFacebook/IconFacebook_size_m.tsx
  src/icons/IconFacebook/IconFacebook_size_s.svg
  src/icons/IconFacebook/IconFacebook_size_s.tsx
  src/icons/IconInstagram/IconInstagram.tsx
  src/icons/IconInstagram/IconInstagram_size_m.svg
  src/icons/IconInstagram/IconInstagram_size_m.tsx
  src/icons/IconInstagram/IconInstagram_size_s.svg
  src/icons/IconInstagram/IconInstagram_size_s.tsx
  src/icons/IconVkontakte/IconVkontakte.tsx
  src/icons/IconVkontakte/IconVkontakte_size_m.svg
  src/icons/IconVkontakte/IconVkontakte_size_m.tsx
  src/icons/IconVkontakte/IconVkontakte_size_s.svg
  src/icons/IconVkontakte/IconVkontakte_size_s.tsx
  src/icons/IconYandexDzen/IconYandexDzen.tsx
  src/icons/IconYandexDzen/IconYandexDzen_size_m.svg
  src/icons/IconYandexDzen/IconYandexDzen_size_m.tsx
  src/icons/IconYandexDzen/IconYandexDzen_size_s.svg
  src/icons/IconYandexDzen/IconYandexDzen_size_s.tsx
  src/icons/IconYoutube/IconYoutube.tsx
  src/icons/IconYoutube/IconYoutube_size_m.svg
  src/icons/IconYoutube/IconYoutube_size_m.tsx
  src/icons/IconYoutube/IconYoutube_size_s.svg
  src/icons/IconYoutube/IconYoutube_size_s.tsx
Labels: feature

#2127 Feat/combobox
  src/components/Combobox/Combobox.tsx
  src/components/Combobox/__stories__/Combobox.docs.mdx
  src/components/Combobox/__stories__/Combobox.stories.tsx
  src/components/Combobox/__stories__/examples/ComboboxExampleOnInputChange/ComboboxExampleOnInputChange.tsx
  src/components/Combobox/helpers.ts
  src/components/Select/Select.tsx
  src/components/Select/__stories__/Select.docs.mdx
  src/components/Select/__stories__/Select.stories.tsx
  src/components/Select/helpers.ts
  src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
  src/components/SelectComponents/SelectLoader/SelectLoader.css
  src/components/SelectComponents/SelectLoader/SelectLoader.tsx
  src/components/UserSelect/UserSelect.tsx
  src/components/UserSelect/__stories__/UserSelect.docs.mdx
  src/components/UserSelect/__stories__/UserSelect.stories.tsx
  src/components/UserSelect/helpers.ts
Labels: feature

#2109 feat(cnMixPopoverAnimate): add animation to many components which use…
  src/components/ProgressStepBarCanary/ProgressStepBarItem/ProgressStepBarItem.tsx
  src/components/SelectComponents/SelectDropdown/SelectDropdown.css
  src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
  src/components/Table/FilterTooltip/TableFilterTooltip.tsx
  src/components/Tabs/MoreItems/TabsMoreItems.css
  src/components/Tabs/MoreItems/TabsMoreItems.tsx
Labels: bug, feature, 🔥🔥 priority

#2086 Test/context menu canary
  src/components/ContextMenu/ContextMenuItem/ContextMenuItem.css
  src/components/ContextMenu/ContextMenuItem/ContextMenuItem.tsx
  src/components/ContextMenu/ContextMenuLevel/ContextMenuLevel.css
  src/components/ContextMenu/ContextMenuLevel/ContextMenuLevel.tsx
  src/components/ContextMenuCanary/__tests__/ContextMenu.test.tsx
Labels: feature
