Repository consta-design-system/uikit, pull requests merged in 2022-02, with the labels that each got.

#1995 feat(ResponsesExit): add new response image
  src/components/Responses/__stories__/Responses.stories.tsx
  src/components/ResponsesExit/ResponsesExit.tsx
  src/responsesImages/ResponsesExit/ResponsesExit.svg
  src/responsesImages/ResponsesExit/ResponsesExit.tsx
  src/responsesImages/ResponsesExit/ResponsesExitSvg.tsx
Labels: feature, 🔥🔥 priority

#1997 docs(DatePicker): edit docs
  src/components/DatePickerCanary/__stories__/DatePicker.docs.mdx
  src/components/DatePickerCanary/__stories__/examples/DatePickerExampleMulti/DatePickerExampleMulti.tsx
Labels: docs

#1998 docs(common): edit links to github
  CHANGELOG.md
  README.md
  docs/common/addComponent/addComponent.stories.mdx
  docs/common/developers/arrangements-for-code-style.stories.mdx
  docs/common/developers/contributors.stories.mdx
  docs/common/developers/design.stories.mdx
  docs/common/developers/review.stories.mdx
  docs/common/icons/icons.stories.mdx
  docs/common/repos/components/ReposData/ReposData.tsx
  docs/common/sla/sla.stories.mdx
  docs/common/work/howToGo.stories.mdx
  docs/common/work/issues.stories.mdx
  docs/thematization/howToCreateYourPreset.stories.mdx
  docs/thematization/whatAreThemes.stories.mdx
  src/components/Table/__stories__/Table.docs.mdx
  src/components/Theme/__stories__/Theme.docs.mdx
  src/hooks/useChoiceGroup/__stories__/useChoiceGroup.stories.mdx
  src/hooks/useChoiceGroupIndexed/__stories__/useChoiceGroupIndexed.stories.mdx
  src/hooks/useClickOutside/__stories__/useClickOutside.stories.mdx
  src/hooks/useGlobalKeys/__stories__/useGlobalKeys.stories.mdx
  src/hooks/useThemeVars/__stories__/useThemeVars.stories.mdx
Labels: docs

#1994 feat(TextField): add new type for autoComplete on TextFiedl
  src/components/EventInterceptor/propsHandlers/useTextFieldEventsHandler.tsx
  src/components/TextField/helpers.ts
  src/utils/types/AutoComplete.ts
Labels: 🔥🔥 priority, improvement

#1978 feat(SnackBar): add progress line timer
  src/components/EventInterceptor/propsHandlers/__tests__/useSnackBarEventsHandler.test.tsx
  src/components/SnackBar/ActionButton/SnackBar-ActionButton.css
  src/components/SnackBar/ActionButton/SnackBar-ActionButton.tsx
  src/components/SnackBar/Item/SnackBar-Item.css
  src/components/SnackBar/SnackBar.css
  src/components/SnackBar/SnackBar.tsx
  src/components/SnackBar/SnackBarActionButton/SnackBarActionButton.css
  src/components/SnackBar/SnackBarActionButton/SnackBarActionButton.tsx
  src/components/SnackBar/SnackBarItem/SnackBarItem.css
  src/components/SnackBar/SnackBarItem/SnackBarItem.tsx
  src/components/SnackBar/SnackBarLine/SnackBarLine.css
  src/components/SnackBar/SnackBarLine/SnackBarLine.tsx
  src/components/SnackBar/SnackBarTimer/SnackBarTimer.css
  src/components/SnackBar/SnackBarTimer/SnackBarTimer.tsx
  src/components/SnackBar/Timer/SnackBar-Timer.css
  src/components/SnackBar/__stories__/SnackBar.docs.mdx
  src/components/SnackBar/__stories__/SnackBar.stories.tsx
  src/components/SnackBar/__stories__/examples/SnackBarExampleButtons/SnackBarExampleButtons.tsx
  src/components/SnackBar/__stories__/examples/SnackBarExampleIcon/SnackBarExampleIcon.tsx
  src/components/SnackBar/__stories__/examples/SnackBarExampleStatus/SnackBarExampleStatus.tsx
  src/components/SnackBar/__stories__/examples/SnackBarExampleTimer/SnackBarExampleTimer.tsx
  src/components/SnackBar/__stories__/examples/SnackBarExampleWithButtons/SnackBarExampleWithButtons.tsx
  src/components/SnackBar/__tests__/SnackBar.test.tsx
  src/components/SnackBar/helper.ts
  src/uiKit/components/ThemePreview/ThemePreview.tsx
Labels: feature, 🔥🔥🔥 priority

#2017 docs(repos): add templates
  docs/common/about/figma.stories.mdx
  docs/common/repos/components/ReposData/ReposData.tsx
  docs/common/repos/repos.stories.mdx
Labels: docs

#2020 fix(ContextMenuItem): fix cascading styles
  src/components/ContextMenu/ContextMenuItem/ContextMenuItem.css
Labels: bug

#2023 docs(Icons): add create icons page
  docs/common/developers/createIcons.stories.mdx
  src/icons/Icon/__stories__/Icon.docs.mdx
Labels: docs

#2038 docs(Responces): add ResponsesExit to the docs
  src/components/Responses/__stories__/Responses.docs.mdx
  src/components/Responses/__stories__/examples/ResponsesExample/ResponsesExample.tsx
Labels: docs

#2040 docs(TextField): add autoComplete to the props table
  src/components/TextField/__stories__/TextField.docs.mdx
Labels: docs

#2048 fix(useTimer): fix bug with memory leak
  src/hooks/useTimer/useTimer.tsx
Labels: bug

#2046 feat(Selects): add new props to all components with SelectDropDown
  src/components/Combobox/Combobox.tsx
  src/components/Combobox/__stories__/Combobox.docs.mdx
  src/components/Combobox/helpers.ts
  src/components/Select/Select.tsx
  src/components/Select/__stories__/Select.docs.mdx
  src/components/Select/helpers.ts
  src/components/SelectComponents/SelectDropdown/SelectDropdown.css
  src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
  src/components/SelectComponents/helpers.ts
  src/components/UserSelect/UserSelect.tsx
  src/components/UserSelect/__stories__/UserSelect.docs.mdx
  src/components/UserSelect/helpers.ts
  src/hooks/useSelect/useSelect.ts
Labels: feature

#2047 fix(useSelect): fix bug with Uncaught TypeError
  src/hooks/useSelect/useSelect.ts
Labels: bug

#2032 refactor(SnackBar): add other props for detecting item props and also update doc
  src/components/EventInterceptor/propsHandlers/__tests__/useSnackBarEventsHandler.test.tsx
  src/components/EventInterceptor/propsHandlers/useSnackBarEventsHandler.tsx
  src/components/SnackBar/SnackBar.tsx
  src/components/SnackBar/SnackBarActionButton/SnackBarActionButton.tsx
  src/components/SnackBar/SnackBarItem/SnackBarItem.tsx
  src/components/SnackBar/SnackBarLine/SnackBarLine.tsx
  src/components/SnackBar/SnackBarTimer/SnackBarTimer.tsx
  src/components/SnackBar/__stories__/SnackBar.docs.mdx
  src/components/SnackBar/__stories__/SnackBar.stories.tsx
  src/components/SnackBar/__stories__/examples/SnackBarExampleButtons/SnackBarExampleButtons.tsx
  src/components/SnackBar/__stories__/examples/SnackBarExampleIcon/SnackBarExampleIcon.tsx
  src/components/SnackBar/__stories__/examples/SnackBarExampleSimple/SnackBarExampleSimple.tsx
  src/components/SnackBar/__stories__/examples/SnackBarExampleStatus/SnackBarExampleStatus.tsx
  src/components/SnackBar/__stories__/examples/SnackBarExampleText/SnackBarExampleText.css
  src/components/SnackBar/__stories__/examples/SnackBarExampleText/SnackBarExampleText.tsx
  src/components/SnackBar/__stories__/examples/SnackBarExampleTimer/SnackBarExampleTimer.tsx
  src/components/SnackBar/__stories__/examples/SnackBarExampleWithButtons/SnackBarExampleWithButtons.css
  src/components/SnackBar/__stories__/examples/SnackBarExampleWithButtons/SnackBarExampleWithButtons.tsx
  src/components/SnackBar/__tests__/SnackBar.test.tsx
  src/components/SnackBar/helper.ts
  src/components/SnackBar/types.ts
  src/uiKit/components/ThemePreview/ThemePreview.tsx
Labels: feature, 🔥🔥 priority

#2072 fix(CssTransition): fix warning with finDOMNode in Transaction children
  src/components/Collapse/CollapseIcon/CollapseIcon.tsx
  src/components/SelectComponents/SelectDropdown/SelectDropdown.tsx
  src/components/SelectComponentsDeprecated/SelectDropdown/SelectDropdown.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/UserSelect/UserSelectItem/UserSelectItem.tsx
  src/components/UserSelectDeprecated/UserSelectItem/UserSelectItem.tsx
Labels: bug

#2081 docs(review): fix link to the Table
  src/components/Table/__stories__/Table.stories.tsx
Labels: docs

#2082 docs(LabelForEmptyItems): edit text
  src/components/Combobox/__stories__/Combobox.docs.mdx
  src/components/Select/__stories__/Select.docs.mdx
  src/components/UserSelect/__stories__/UserSelect.docs.mdx
Labels: docs
