Repository consta-design-system/uikit, pull requests merged in 2022-11, with the labels that each got.

#2726 feat(Icons): update types for usage icons from @consta/icons
  src/icons/Icon/Icon.tsx
Labels: feature

#2747 fix(Text): fix quotes in the examples
  src/components/Text/__stand__/examples/TextExampleAlign/TextExampleAlign.tsx
  src/components/Text/__stand__/examples/TextExampleLineheight/TextExampleLineheight.tsx
  src/components/Text/__stand__/examples/TextExampleSize/TextExampleSize.tsx
  src/components/Text/__stand__/examples/TextExampleSpacing/TextExampleSpacing.tsx
  src/components/Text/__stand__/examples/TextExampleView/TextExampleView.tsx
  src/components/Text/__stand__/examples/TextExampleWeight/TextExampleWeight.tsx
Labels: bug, docs

#2746 fix(useChoiceGroup): fix bug with false type variable
  src/hooks/useChoiceGroup/__tests__/useChoiceGroup.test.tsx
  src/hooks/useChoiceGroup/useChoiceGroup.tsx
Labels: bug

#2735 docs(review): add images
  src/components/RadioGroupDeprecated/__stand__/RadioGroupDeprecated.image.svg
  src/components/StepsDeprecated/__stand__/StepsDeprecated.image.svg
  src/components/SwitchGroupDeprecated/__stand__/SwitchGroupDeprecated.image.svg
  src/components/TabsDeprecated/__stand__/TabsDeprecated.image.svg
  src/icons/Icon/__stand__/icon.image.svg
Labels: docs

#2732 fix(Table): fix 'level' accessor
  src/components/Table/Table.tsx
  src/components/Table/helpers.ts
Labels: bug

#2730 feat(SnackBar): add prop form
  src/components/SnackBar/SnackBar.tsx
  src/components/SnackBar/SnackBarItem/SnackBarItem.css
  src/components/SnackBar/SnackBarItem/SnackBarItem.tsx
  src/components/SnackBar/__stand__/SnackBar.dev.stand.mdx
  src/components/SnackBar/__stand__/SnackBar.variants.tsx
  src/components/SnackBar/__stand__/examples/SnackBarExampleForm/SnackBarExampleForm.tsx
  src/components/SnackBar/types.ts
Labels: feature

#2748 fix(DateTime): fix pading for date-time view
  src/components/DateTime/DateTimeTypeDateTime/DateTimeTypeDateTime.css
  src/components/DateTime/DateTimeTypeTime/DateTimeTypeTime.css
Labels: bug

#2733 feat(Collapse): rewrite label from string to ReactNode
  src/components/Collapse/Collapse.tsx
  src/components/Collapse/CollapseIcon/CollapseIcon.tsx
  src/components/Collapse/__stand__/Collapse.dev.stand.mdx
  src/components/Collapse/__stand__/examples/CollapseExampleLabel/CollapseExampleLabel.css
  src/components/Collapse/__stand__/examples/CollapseExampleLabel/CollapseExampleLabel.tsx
  src/components/Collapse/types.ts
  src/components/CollapseGroup/helpers.ts
Labels: feature

#2768 feat(Table): add colSpan for columns and also add variants with examples
  src/components/Table/Cell/TableCell.css
  src/components/Table/Table.tsx
  src/components/Table/__mock__/data.mock.tsx
  src/components/Table/__stand__/Table.dev.stand.mdx
  src/components/Table/__stand__/Table.variants.tsx
  src/components/Table/__stand__/examples/TableExampleRowSpan/TableExampleRowSpan.tsx
  src/components/Table/__stand__/variants/TableVariantWithColSpan/TableVariantWithColSpan.tsx
  src/components/Table/__stand__/variants/useVariants/useVariants.ts
  src/components/Table/helpers.ts
Labels: feature

#2789 feat(Collapse): add content size tracking and new prop maxContentHeeight
  src/components/Collapse/Collapse.css
  src/components/Collapse/Collapse.tsx
  src/components/Collapse/__stand__/Collapse.dev.stand.mdx
  src/components/Collapse/__stand__/Collapse.variants.css
  src/components/Collapse/__stand__/Collapse.variants.tsx
  src/components/Collapse/types.ts
Labels: feature

#2798 docs(useBreakpoints): edit doc
  src/hooks/useBreakpoints/__stand__/useBreakpoints.stand.mdx
  src/hooks/useComponentBreakpoints/__stand__/useComponentBreakpoints.stand.mdx
Labels: docs

#2799 docs: add how to use tab
  src/components/Attachment/__stand__/Attachment.dev.stand.mdx
  src/components/Attachment/__stand__/Attachment.use.stand.mdx
  src/components/Badge/__stand__/Badge.stand.mdx
  src/components/Badge/__stand__/Badge.use.stand.mdx
  src/components/Button/__stand__/Button.dev.stand.mdx
  src/components/Button/__stand__/Button.stand.mdx
  src/components/Button/__stand__/Button.use.stand.mdx
  src/components/Button/__stand__/examples/ButtonExampleName/ButtonExampleName.tsx
  src/components/Card/__stand__/Card.dev.stand.mdx
  src/components/CheckboxGroup/__stand__/CheckboxGroup.stand.mdx
  src/components/CheckboxGroup/__stand__/CheckboxGroup.use.stand.mdx
  src/components/ChoiceGroup/__stand__/ChoiceGroup.stand.mdx
  src/components/ChoiceGroup/__stand__/ChoiceGroup.use.stand.mdx
  src/components/DatePicker/__stand__/DatePicker.dev.stand.mdx
  src/components/DatePicker/__stand__/DatePicker.stand.mdx
  src/components/FieldGroup/__stand__/FieldGroup.dev.stand.mdx
  src/components/Header/__stand__/Header.dev.stand.mdx
  src/components/Informer/__stand__/Informer.stand.mdx
  src/components/Informer/__stand__/Informer.use.stand.mdx
  src/components/ProgressStepBar/__stand__/ProgressStepBar.stand.mdx
  src/components/ProgressStepBar/__stand__/ProgressStepBar.use.stand.mdx
  src/components/RadioGroup/__stand__/RadioGroup.stand.mdx
  src/components/RadioGroup/__stand__/RadioGroup.use.stand.mdx
  src/components/RadioGroupDeprecated/__stand__/RadioGroupDeprecated.stand.mdx
  src/components/RadioGroupDeprecated/__stand__/RadioGroupDeprecated.use.stand.mdx
  src/components/Skeleton/__stand__/Skeleton.dev.stand.mdx
  src/components/Skeleton/__stand__/Skeleton.use.stand.mdx
  src/components/Tag/__stand__/Tag.dev.stand.mdx
  src/components/ThemeToggler/__stand__/ThemeToggler.dev.stand.mdx
  src/components/Tooltip/__stand__/Tooltip.dev.stand.mdx
  src/components/User/__stand__/User.dev.stand.mdx
  src/components/User/__stand__/examples/UserExampleSize/UserExampleSize.tsx
  src/stand/standConfig.ts
Labels: docs

#2790 feat(Checkbox): add 's' and 'xs' size
  src/components/Checkbox/Checkbox.css
  src/components/Checkbox/Checkbox.tsx
  src/components/Checkbox/__stand__/Checkbox.dev.stand.mdx
  src/components/Checkbox/__stand__/examples/CheckboxExampleSize/CheckboxExampleSize.tsx
  src/components/Theme/_control/Theme_control_gpnDefault.css
Labels: feature

#2797 fix(Table): fix border on multi level header
  src/components/Table/Header/TableHeader.tsx
  src/components/Table/__mock__/data.mock.tsx
  src/components/Table/helpers.ts
Labels: bug
