Repository consta-design-system/uikit, pull requests merged in 2022-08, with the labels that each got.

#2451 docs(common): update libraries lists and review
  docs/common/figma/components/FigmaData/FigmaData.tsx
  docs/common/figma/figma.stories.mdx
  docs/common/fonts.stories.mdx
  docs/common/repos/components/ReposData/ReposData.tsx
  src/icons/Icon/__stories__/Icons.stories.tsx
  src/uiKit/components/ComponentsGridWithData/data/additionalData.ts
  src/uiKit/components/ComponentsGridWithData/data/data.ts
  src/uiKit/components/ComponentsGridWithData/data/imagesForAdditionalData/MixPlotImage.tsx
  src/uiKit/components/ComponentsGridWithData/data/imagesForAdditionalData/ReactBigCalendarImage.tsx
Labels: docs

#2454 fix(Collapse): fix bug with color of icon on dark theme
  src/components/Collapse/CollapseIcon/CollapseIcon.css
Labels: bug

#2458 fix(Steps): fix crush with using google translate
  src/components/Steps/StepsStep/StepsStep.tsx
  src/components/StepsCanary/StepsStep/StepsStep.tsx
Labels: bug

#2459 docs(components): fix figma links
  src/components/Attachment/__stories__/Attachment.stories.tsx
  src/components/DatePickerCanary/__stories__/DatePicker.stories.tsx
  src/components/FieldGroup/__stories__/FieldGroup.stories.tsx
  src/components/ProgressLine/__stories__/ProgressLine.stories.tsx
  src/components/Skeleton/__stories__/Skeleton.stories.tsx
  src/components/Text/__stories__/Text.stories.tsx
  src/components/Tooltip/__stories__/Tooltip.stories.tsx
Labels: docs

#2455 feat(Badge): add xs size
  src/components/Badge/Badge.css
  src/components/Badge/Badge.tsx
  src/components/Badge/__stories__/Badge.docs.mdx
  src/components/Badge/__stories__/examples/BadgeExampleSize/BadgeExampleSize.tsx
Labels: feature

#2460 feat(Modal): add afterClose prop
  src/components/Modal/Modal.tsx
  src/components/Sidebar/Sidebar.tsx
Labels: feature

#2468 Feat/progress line
  src/components/ProgressLine/ProgressLine.css
  src/components/ProgressLine/ProgressLine.tsx
  src/components/ProgressLine/__stories__/ProgressLine.docs.mdx
  src/components/ProgressLine/__stories__/ProgressLine.stories.tsx
  src/components/ProgressLine/__stories__/examples/ProgressLineExampleMode/ProgressLineExampleMode.tsx
  src/components/ProgressLine/helpers.ts
  src/components/ProgressLine/types.ts
Labels: feature

#2467 docs(custom): add docs examples
  src/components/Button/__stand__/Button.design.stand.mdx
  src/components/Button/__stand__/Button.dev.stand.mdx
  src/components/Button/__stand__/Button.stand.mdx
  src/components/Button/__stand__/Button.stand.tsx
  src/components/Switch/__stand__/Switch.design.stand.mdx
  src/components/Switch/__stand__/Switch.dev.stand.mdx
  src/components/Switch/__stand__/Switch.stand.mdx
  src/components/Switch/__stand__/Switch.stand.tsx
Labels: docs

#2471 feat(AvatarGroup): add component for avatar grouping
  src/components/AvatarGroup/AvatarGroup.css
  src/components/AvatarGroup/AvatarGroup.tsx
  src/components/AvatarGroup/__mocks__/mock.data.ts
  src/components/AvatarGroup/__stories__/AvatarGroup.docs.mdx
  src/components/AvatarGroup/__stories__/AvatarGroup.image.svg
  src/components/AvatarGroup/__stories__/AvatarGroup.stories.tsx
  src/components/AvatarGroup/__stories__/examples/AvatarGroupExampleCount/AvatarGroupExampleCount.tsx
  src/components/AvatarGroup/__stories__/examples/AvatarGroupExampleForm/AvatarGroupExampleForm.tsx
  src/components/AvatarGroup/__stories__/examples/AvatarGroupExampleSize/AvatarGroupExampleSize.tsx
  src/components/AvatarGroup/__tests__/AvatarGroup.test.tsx
  src/components/AvatarGroup/helpers.ts
  src/components/AvatarGroup/types.ts
Labels: feature

#2484 docs(custom): avatar
  src/components/Avatar/__stand__/Avatar.design.stand.mdx
  src/components/Avatar/__stand__/Avatar.dev.stand.mdx
  src/components/Avatar/__stand__/Avatar.image.svg
  src/components/Avatar/__stand__/Avatar.stand.mdx
  src/components/Avatar/__stand__/Avatar.stand.tsx
  src/components/Avatar/__stand__/examples/AvatarExampleForm/AvatarExampleForm.tsx
  src/components/Avatar/__stand__/examples/AvatarExampleImage/AvatarExampleImage.tsx
  src/components/Avatar/__stand__/examples/AvatarExampleSize/AvatarExampleSize.tsx
Labels: docs

#2485 docs(custom): userSelect
  src/components/UserSelect/__stand__/UserSelect.design.stand.mdx
  src/components/UserSelect/__stand__/UserSelect.dev.stand.mdx
  src/components/UserSelect/__stand__/UserSelect.image.svg
  src/components/UserSelect/__stand__/UserSelect.stand.mdx
  src/components/UserSelect/__stand__/UserSelect.stand.tsx
  src/components/UserSelect/__stand__/examples/UserSelectExampleCaption/UserSelectExampleCaption.tsx
  src/components/UserSelect/__stand__/examples/UserSelectExampleCreate/UserSelectExampleCreate.tsx
  src/components/UserSelect/__stand__/examples/UserSelectExampleCustomTypes/UserSelectExampleCustomTypes.tsx
  src/components/UserSelect/__stand__/examples/UserSelectExampleDisabled/UserSelectExampleDisabled.tsx
  src/components/UserSelect/__stand__/examples/UserSelectExampleDisabledItem/UserSelectExampleDisabledItem.tsx
  src/components/UserSelect/__stand__/examples/UserSelectExampleForm/UserSelectExampleForm.tsx
  src/components/UserSelect/__stand__/examples/UserSelectExampleGroups/UserSelectExampleGroups.tsx
  src/components/UserSelect/__stand__/examples/UserSelectExampleItems/UserSelectExampleItems.tsx
  src/components/UserSelect/__stand__/examples/UserSelectExampleLabel/UserSelectExampleLabel.tsx
  src/components/UserSelect/__stand__/examples/UserSelectExampleMultiple/UserSelectExampleMultiple.tsx
  src/components/UserSelect/__stand__/examples/UserSelectExamplePlaceholder/UserSelectExamplePlaceholder.tsx
  src/components/UserSelect/__stand__/examples/UserSelectExampleRenderItem/UserSelectExampleRenderItem.css
  src/components/UserSelect/__stand__/examples/UserSelectExampleRenderItem/UserSelectExampleRenderItem.tsx
  src/components/UserSelect/__stand__/examples/UserSelectExampleRenderValue/UserSelectExampleRenderValue.css
  src/components/UserSelect/__stand__/examples/UserSelectExampleRenderValue/UserSelectExampleRenderValue.tsx
  src/components/UserSelect/__stand__/examples/UserSelectExampleSize/UserSelectExampleSize.tsx
  src/components/UserSelect/__stand__/examples/UserSelectExampleStatus/UserSelectExampleStatus.tsx
  src/components/UserSelect/__stand__/examples/UserSelectExampleView/UserSelectExampleView.tsx
Labels: docs

#2486 feat(custom): User
  src/components/User/__stand__/User.design.stand.mdx
  src/components/User/__stand__/User.dev.stand.mdx
  src/components/User/__stand__/User.image.svg
  src/components/User/__stand__/User.stand.mdx
  src/components/User/__stand__/User.stand.tsx
  src/components/User/__stand__/examples/UserExampleArrow/UserExampleArrow.tsx
  src/components/User/__stand__/examples/UserExampleAvatar/UserExampleAvatar.tsx
  src/components/User/__stand__/examples/UserExampleName/UserExampleName.tsx
  src/components/User/__stand__/examples/UserExampleSize/UserExampleSize.tsx
  src/components/User/__stand__/examples/UserExampleStatus/UserExampleStatus.tsx
  src/components/User/__stand__/examples/UserExampleView/UserExampleView.tsx
Labels: docs

#2487 docs(custom): button
  src/components/Button/__stand__/Button.dev.stand.mdx
  src/components/Button/__stand__/Button.stand.mdx
  src/components/Button/__stand__/examples/ButtonExampleAdaptive/ButtonExampleAdaptive.tsx
  src/components/Button/__stand__/examples/ButtonExampleForm/ButtonExampleForm.tsx
  src/components/Button/__stand__/examples/ButtonExampleIcon/ButtonExampleIcon.tsx
  src/components/Button/__stand__/examples/ButtonExampleLoading/ButtonExampleLoading.tsx
  src/components/Button/__stand__/examples/ButtonExampleName/ButtonExampleName.tsx
  src/components/Button/__stand__/examples/ButtonExampleSize/ButtonExampleSize.tsx
  src/components/Button/__stand__/examples/ButtonExampleView/ButtonExampleView.tsx
  src/components/Button/__stories__/examples/ButtonExampleBasic/ButtonExampleBasic.tsx
  src/components/Button/__stories__/examples/ButtonExampleView/ButtonExampleView.tsx
Labels: docs

#2488 docs(custom): tooltip
  src/components/Tooltip/__stand__/Tooltip.design.stand.mdx
  src/components/Tooltip/__stand__/Tooltip.dev.stand.mdx
  src/components/Tooltip/__stand__/Tooltip.image.svg
  src/components/Tooltip/__stand__/Tooltip.stand.mdx
  src/components/Tooltip/__stand__/Tooltip.stand.tsx
  src/components/Tooltip/__stand__/examples/TooltipPosition/TooltipPosition.css
  src/components/Tooltip/__stand__/examples/TooltipPosition/TooltipPosition.tsx
Labels: docs

#2489 docs(custom): timer
  src/components/Timer/__stand__/Timer.design.stand.mdx
  src/components/Timer/__stand__/Timer.dev.stand.mdx
  src/components/Timer/__stand__/Timer.image.svg
  src/components/Timer/__stand__/Timer.stand.mdx
  src/components/Timer/__stand__/Timer.stand.tsx
  src/components/Timer/__stand__/examples/TimerExampleProgress/TimerExampleProgress.tsx
  src/components/Timer/__stand__/examples/TimerExampleSeconds/TimerExampleSeconds.tsx
  src/components/Timer/__stand__/examples/TimerExampleSize/TimerExampleSize.tsx
Labels: docs

#2490 docs(custom): themeToggler
  babel.config.js
  src/components/ContextMenu/ContextMenuLevels/ContextMenuLevels.tsx
  src/components/ContextMenu/helpers.ts
  src/components/ContextMenu/types.ts
  src/components/ThemeToggler/ThemeToggler.tsx
  src/components/ThemeToggler/__stand__/ThemeToggler.design.stand.mdx
  src/components/ThemeToggler/__stand__/ThemeToggler.dev.stand.mdx
  src/components/ThemeToggler/__stand__/ThemeToggler.image.svg
  src/components/ThemeToggler/__stand__/ThemeToggler.stand.mdx
  src/components/ThemeToggler/__stand__/ThemeToggler.stand.tsx
  src/components/ThemeToggler/__stand__/examples/ThemeTogglerExampleDefault/ThemeTogglerExampleDefault.css
  src/components/ThemeToggler/__stand__/examples/ThemeTogglerExampleDefault/ThemeTogglerExampleDefault.tsx
  src/components/ThemeToggler/__stand__/examples/ThemeTogglerExampleGetters/ThemeTogglerExampleGetters.css
  src/components/ThemeToggler/__stand__/examples/ThemeTogglerExampleGetters/ThemeTogglerExampleGetters.tsx
  src/components/ThemeToggler/__stand__/examples/ThemeTogglerExampleQuantity/ThemeTogglerExampleQuantity.css
  src/components/ThemeToggler/__stand__/examples/ThemeTogglerExampleQuantity/ThemeTogglerExampleQuantity.tsx
  src/components/ThemeToggler/__stand__/examples/ThemeTogglerExampleSize/ThemeTogglerExampleSize.css
  src/components/ThemeToggler/__stand__/examples/ThemeTogglerExampleSize/ThemeTogglerExampleSize.tsx
  src/components/ThemeToggler/__tests__/ThemeToggler.test.tsx
Labels: docs

#2491 docs(custom): theme
  src/components/Theme/__stand__/Theme.design.stand.mdx
  src/components/Theme/__stand__/Theme.dev.stand.mdx
  src/components/Theme/__stand__/Theme.image.svg
  src/components/Theme/__stand__/Theme.stand.mdx
  src/components/Theme/__stand__/Theme.stand.tsx
  src/components/Theme/__stand__/examples/ThemeExampleColors/ThemeExampleColors.css
  src/components/Theme/__stand__/examples/ThemeExampleColors/ThemeExampleColors.tsx
  src/components/Theme/__stand__/examples/ThemeExampleRoot/ThemeExampleRoot.css
  src/components/Theme/__stand__/examples/ThemeExampleRoot/ThemeExampleRoot.tsx
Labels: docs

#2492 docs(custom): textField
  src/components/TextField/__stand__/TextField.design.stand.mdx
  src/components/TextField/__stand__/TextField.dev.stand.mdx
  src/components/TextField/__stand__/TextField.image.svg
  src/components/TextField/__stand__/TextField.stand.mdx
  src/components/TextField/__stand__/TextField.stand.tsx
  src/components/TextField/__stand__/examples/TextFieldExampleCaption/TextFieldExampleCaption.tsx
  src/components/TextField/__stand__/examples/TextFieldExampleFocus/TextFieldExampleFocus.tsx
  src/components/TextField/__stand__/examples/TextFieldExampleForm/TextFieldExampleForm.tsx
  src/components/TextField/__stand__/examples/TextFieldExampleLabel/TextFieldExampleLabel.css
  src/components/TextField/__stand__/examples/TextFieldExampleLabel/TextFieldExampleLabel.tsx
  src/components/TextField/__stand__/examples/TextFieldExampleRequired/TextFieldExampleRequired.tsx
  src/components/TextField/__stand__/examples/TextFieldExampleSize/TextFieldExampleSize.tsx
  src/components/TextField/__stand__/examples/TextFieldExampleStatus/TextFieldExampleStatus.tsx
  src/components/TextField/__stand__/examples/TextFieldExampleStepArray/TextFieldExampleStepArray.tsx
  src/components/TextField/__stand__/examples/TextFieldExampleText/TextFieldExampleText.tsx
  src/components/TextField/__stand__/examples/TextFieldExampleType/TextFieldExampleType.tsx
  src/components/TextField/__stand__/examples/TextFieldExampleView/TextFieldExampleView.tsx
Labels: docs

#2493 docs(custom): badge
  src/components/Badge/__stand__/Badge.design.stand.mdx
  src/components/Badge/__stand__/Badge.dev.stand.mdx
  src/components/Badge/__stand__/Badge.image.svg
  src/components/Badge/__stand__/Badge.stand.mdx
  src/components/Badge/__stand__/Badge.stand.tsx
Labels: docs

#2495 docs(components): tag
  src/components/Tag/__stand__/Tag.design.stand.mdx
  src/components/Tag/__stand__/Tag.dev.stand.mdx
  src/components/Tag/__stand__/Tag.image.svg
  src/components/Tag/__stand__/Tag.stand.mdx
  src/components/Tag/__stand__/Tag.stand.tsx
  src/components/Tag/__stand__/examples/TagExampleGroup/TagExampleGroup.tsx
  src/components/Tag/__stand__/examples/TagExampleIcon/TagExampleIcon.tsx
  src/components/Tag/__stand__/examples/TagExampleMode/TagExampleMode.tsx
  src/components/Tag/__stand__/examples/TagExampleSize/TagExampleSize.tsx
  src/components/Tag/__stand__/examples/TagExampleText/TagExampleText.tsx
Labels: docs

#2497 docs(custom): card
  src/components/Card/__stand__/Card.design.stand.mdx
  src/components/Card/__stand__/Card.dev.stand.mdx
  src/components/Card/__stand__/Card.image.svg
  src/components/Card/__stand__/Card.stand.mdx
  src/components/Card/__stand__/Card.stand.tsx
  src/components/Card/__stories__/examples/CardExample/CardExample.tsx
Labels: docs

#2494 docs(custom): text
  src/components/Text/__stand__/Text.design.stand.mdx
  src/components/Text/__stand__/Text.dev.stand.mdx
  src/components/Text/__stand__/Text.image copy.svg
  src/components/Text/__stand__/Text.image.svg
  src/components/Text/__stand__/Text.stand.mdx
  src/components/Text/__stand__/Text.stand.tsx
  src/components/Text/__stand__/examples/TextExampleAlign/TextExampleAlign.tsx
  src/components/Text/__stand__/examples/TextExampleCombinedWeightAndStyle/TextExampleCombinedWeightAndStyle.tsx
  src/components/Text/__stand__/examples/TextExampleCursor/TextExampleCursor.tsx
  src/components/Text/__stand__/examples/TextExampleDecoration/TextExampleDecoration.tsx
  src/components/Text/__stand__/examples/TextExampleHeadingAndParagraph/TextExampleHeadingAndParagraph.tsx
  src/components/Text/__stand__/examples/TextExampleLabelAndData/TextExampleLabelAndData.tsx
  src/components/Text/__stand__/examples/TextExampleLineheight/TextExampleLineheight.tsx
  src/components/Text/__stand__/examples/TextExampleSize/TextExampleSize.tsx
  src/components/Text/__stand__/examples/TextExampleSpacing/TextExampleSpacing.tsx
  src/components/Text/__stand__/examples/TextExampleStyle/TextExampleStyle.tsx
  src/components/Text/__stand__/examples/TextExampleTransform/TextExampleTransform.tsx
  src/components/Text/__stand__/examples/TextExampleTruncate/TextExampleTruncate.tsx
  src/components/Text/__stand__/examples/TextExampleView/TextExampleView.tsx
  src/components/Text/__stand__/examples/TextExampleWeight/TextExampleWeight.tsx
Labels: docs

#2496 docs(custom): tabs
  src/components/Tabs/__stand__/Tabs.design.stand.mdx
  src/components/Tabs/__stand__/Tabs.dev.stand.mdx
  src/components/Tabs/__stand__/Tabs.image.svg
  src/components/Tabs/__stand__/Tabs.stand.mdx
  src/components/Tabs/__stand__/Tabs.stand.tsx
  src/components/Tabs/__stand__/examples/TabsExample/TabsExample.tsx
  src/components/Tabs/__stand__/examples/TabsExampleFitModeDropdown/TabsExampleFitModeDropdown.tsx
  src/components/Tabs/__stand__/examples/TabsExampleFitModeScroll/TabsExampleFitModeScroll.tsx
  src/components/Tabs/__stand__/examples/TabsExampleIcon/TabsExampleIcon.tsx
  src/components/Tabs/__stand__/examples/TabsExampleLinePosition/TabsExampleLinePosition.tsx
  src/components/Tabs/__stand__/examples/TabsExampleRenderItem/TabsExampleRenderItem.tsx
  src/components/Tabs/__stand__/examples/TabsExampleSize/TabsExampleSize.tsx
  src/components/Tabs/__stand__/examples/TabsExampleView/TabsExampleView.tsx
Labels: docs

#2498 docs(custom): table
  src/components/Table/__stand__/Table.design.stand.mdx
  src/components/Table/__stand__/Table.dev.stand.mdx
  src/components/Table/__stand__/Table.image.svg
  src/components/Table/__stand__/Table.stand.mdx
  src/components/Table/__stand__/Table.stand.tsx
  src/components/Table/__stand__/examples/TableExampleAlign/TableExampleAlign.tsx
  src/components/Table/__stand__/examples/TableExampleBasic/TableExampleBasic.tsx
  src/components/Table/__stand__/examples/TableExampleBorder/TableExampleBorder.tsx
  src/components/Table/__stand__/examples/TableExampleFilter/TableExampleFilter.tsx
  src/components/Table/__stand__/examples/TableExampleIsResizable/TableExampleIsResizable.tsx
  src/components/Table/__stand__/examples/TableExampleMerge/TableExampleMerge.tsx
  src/components/Table/__stand__/examples/TableExampleOnSortBy/TableExampleOnSortBy.tsx
  src/components/Table/__stand__/examples/TableExampleRenderCell/TableExampleRenderCell.tsx
  src/components/Table/__stand__/examples/TableExampleSize/TableExampleSize.tsx
  src/components/Table/__stand__/examples/TableExampleSort/TableExampleSort.tsx
  src/components/Table/__stand__/examples/TableExampleZebraStriped/TableExampleZebraStriped.tsx
  src/components/Table/__stand__/examples/WithAdditionalClassName/WithAdditionalClassName.css
  src/components/Table/__stand__/examples/WithAdditionalClassName/WithAdditionalClassName.tsx
  src/components/Table/__stand__/examples/WithHandleCellClick.tsx
Labels: docs

#2500 docs(custom): checkbox
  src/components/Checkbox/__stand__/Checkbox.design.stand.mdx
  src/components/Checkbox/__stand__/Checkbox.dev.stand.mdx
  src/components/Checkbox/__stand__/Checkbox.image.svg
  src/components/Checkbox/__stand__/Checkbox.stand.mdx
  src/components/Checkbox/__stand__/Checkbox.stand.tsx
  src/components/Checkbox/__stand__/examples/CheckboxExampleAlign/CheckboxExampleAlign.tsx
  src/components/Checkbox/__stand__/examples/CheckboxExampleName/CheckboxExampleName.tsx
  src/components/Checkbox/__stand__/examples/CheckboxExampleSize/CheckboxExampleSize.tsx
  src/components/Checkbox/__stand__/examples/CheckboxExampleStatus/CheckboxExampleStatus.tsx
  src/components/Checkbox/__stand__/examples/CheckboxExampleView/CheckboxExampleView.tsx
Labels: docs

#2501 docs(custom): checkboxgroup
  .husky/pre-commit
  .husky/pre-push
  src/components/CheckboxGroup/__stand__/CheckboxGroup.design.stand.mdx
  src/components/CheckboxGroup/__stand__/CheckboxGroup.dev.stand.mdx
  src/components/CheckboxGroup/__stand__/CheckboxGroup.image.svg
  src/components/CheckboxGroup/__stand__/CheckboxGroup.stand.mdx
  src/components/CheckboxGroup/__stand__/CheckboxGroup.stand.tsx
  src/components/CheckboxGroup/__stand__/examples/CheckboxGroupExampleDirection/CheckboxGroupExampleDirection.tsx
  src/components/CheckboxGroup/__stand__/examples/CheckboxGroupExampleDisabled/CheckboxGroupExampleDisabled.tsx
  src/components/CheckboxGroup/__stand__/examples/CheckboxGroupExampleName/CheckboxGroupExampleName.tsx
  src/components/CheckboxGroup/__stand__/examples/CheckboxGroupExampleSize/CheckboxGroupExampleSize.tsx
  src/components/CheckboxGroup/__stand__/examples/CheckboxGroupExampleView/CheckboxGroupExampleView.tsx
Labels: docs

#2511 docs(custom): contextmenu
  src/components/ContextMenu/__stand__/ContextMenu.design.stand.mdx
  src/components/ContextMenu/__stand__/ContextMenu.dev.stand.mdx
  src/components/ContextMenu/__stand__/ContextMenu.image.svg
  src/components/ContextMenu/__stand__/ContextMenu.stand.mdx
  src/components/ContextMenu/__stand__/ContextMenu.stand.tsx
  src/components/ContextMenu/__stories__/examples/ContextMenuExampleDefault/ContextMenuExampleDefault.tsx
  src/components/ContextMenu/__stories__/examples/ContextMenuExampleLabel/ContextMenuExampleLabel.tsx
  src/components/ContextMenu/__stories__/examples/ContextMenuExampleSide/ContextMenuExampleSide.tsx
  src/components/ContextMenu/__stories__/examples/ContextMenuExampleSize/ContextMenuExampleSize.tsx
Labels: docs

#2517 docs(custom): skeleton
  src/components/Skeleton/__stand__/Skeleton.design.stand.mdx
  src/components/Skeleton/__stand__/Skeleton.dev.stand.mdx
  src/components/Skeleton/__stand__/Skeleton.image.svg
  src/components/Skeleton/__stand__/Skeleton.stand.mdx
  src/components/Skeleton/__stand__/Skeleton.stand.tsx
  src/components/Skeleton/__stand__/examples/SkeletonExampleAvatar/SkeletonExampleAvatar.css
  src/components/Skeleton/__stand__/examples/SkeletonExampleAvatar/SkeletonExampleAvatar.tsx
  src/components/Skeleton/__stand__/examples/SkeletonExampleImageAndText.tsx
Labels: docs

#2518 docs(custom): sidebar
  src/components/Sidebar/__stand__/Sidebar.design.stand.mdx
  src/components/Sidebar/__stand__/Sidebar.dev.stand.mdx
  src/components/Sidebar/__stand__/Sidebar.image.svg
  src/components/Sidebar/__stand__/Sidebar.stand.mdx
  src/components/Sidebar/__stand__/Sidebar.stand.tsx
  src/components/Sidebar/__stand__/examples/SidebarExample/SidebarExample.css
  src/components/Sidebar/__stand__/examples/SidebarExample/SidebarExample.tsx
Labels: docs

#2521 docs(custom): datetime
  src/components/DateTime/__stand__/DateTime.design.stand.mdx
  src/components/DateTime/__stand__/DateTime.dev.stand.mdx
  src/components/DateTime/__stand__/DateTime.image.svg
  src/components/DateTime/__stand__/DateTime.stand.mdx
  src/components/DateTime/__stand__/DateTime.stand.tsx
  src/components/DateTime/__stories__/examples/DateTimeExampleDateMin/DateTimeExampleDateMin.tsx
  src/components/DateTime/__stories__/examples/DateTimeExampleEvents/DateTimeExampleEvents.tsx
  src/components/DateTime/__stories__/examples/DateTimeExampleLocale/DateTimeExampleLocale.tsx
  src/components/DateTime/__stories__/examples/DateTimeExampleMultiplicity/DateTimeExampleMultiplicity.tsx
  src/components/DateTime/__stories__/examples/DateTimeExampleView/DateTimeExampleView.tsx
Labels: docs

#2523 docs(custom): drgndropfield
  src/components/DragNDropField/__stand__/DragNDropField.design.stand.mdx
  src/components/DragNDropField/__stand__/DragNDropField.dev.stand.mdx
  src/components/DragNDropField/__stand__/DragNDropField.image.svg
  src/components/DragNDropField/__stand__/DragNDropField.stand.mdx
  src/components/DragNDropField/__stand__/DragNDropField.stand.tsx
  src/components/DragNDropField/__stories__/examples/DragNDropFieldExampleAccept/DragNDropFieldExampleAccept.tsx
  src/components/DragNDropField/__stories__/examples/DragNDropFieldExampleErrorMessages/DragNDropFieldExampleErrorMessages.tsx
  src/components/DragNDropField/__stories__/examples/DragNDropFieldExampleMaxSize/DragNDropFieldExampleMaxSize.tsx
  src/components/DragNDropField/__stories__/examples/DragNDropFieldExampleMultiple/DragNDropFieldExampleMultiple.tsx
Labels: docs

#2524 docs(custom): radioGroupDeprecated
  src/components/RadioGroupDeprecated/__stand__/RadioGroup.image.svg
  src/components/RadioGroupDeprecated/__stand__/RadioGroupDeprecated.design.stand.mdx
  src/components/RadioGroupDeprecated/__stand__/RadioGroupDeprecated.dev.stand.mdx
  src/components/RadioGroupDeprecated/__stand__/RadioGroupDeprecated.stand.mdx
  src/components/RadioGroupDeprecated/__stand__/RadioGroupDeprecated.stand.tsx
  src/components/RadioGroupDeprecated/__stand__/examples/RadioGroupExampleAlign/RadioGroupExampleAlign.tsx
  src/components/RadioGroupDeprecated/__stand__/examples/RadioGroupExampleDisabled/RadioGroupExampleDisabled.tsx
  src/components/RadioGroupDeprecated/__stand__/examples/RadioGroupExampleSize/RadioGroupExampleSize.tsx
  src/components/RadioGroupDeprecated/__stand__/examples/RadioGroupExampleUse/RadioGroupExampleUse.tsx
  src/components/RadioGroupDeprecated/__stand__/examples/RadioGroupExampleView/RadioGroupExampleView.tsx
Labels: docs

#2526 docs(custom): radioGroup
  src/components/RadioGroup/__stand__/RadioGroup.design.stand.mdx
  src/components/RadioGroup/__stand__/RadioGroup.dev.stand.mdx
  src/components/RadioGroup/__stand__/RadioGroup.image.svg
  src/components/RadioGroup/__stand__/RadioGroup.stand.mdx
  src/components/RadioGroup/__stand__/RadioGroup.stand.tsx
  src/components/RadioGroup/__stand__/examples/RadioGroupExampleAlign/RadioGroupExampleAlign.tsx
  src/components/RadioGroup/__stand__/examples/RadioGroupExampleDisabled/RadioGroupExampleDisabled.tsx
  src/components/RadioGroup/__stand__/examples/RadioGroupExampleSize/RadioGroupExampleSize.tsx
  src/components/RadioGroup/__stand__/examples/RadioGroupExampleUse/RadioGroupExampleUse.tsx
  src/components/RadioGroup/__stand__/examples/RadioGroupExampleView/RadioGroupExampleView.tsx
Labels: docs

#2527 docs(custom): radio
  src/components/Radio/__stand__/Radio.design.stand.mdx
  src/components/Radio/__stand__/Radio.dev.stand.mdx
  src/components/Radio/__stand__/Radio.image.svg
  src/components/Radio/__stand__/Radio.stand.mdx
  src/components/Radio/__stand__/Radio.stand.tsx
  src/components/Radio/__stand__/examples/RadioExampleAlign/RadioExampleAlign.tsx
  src/components/Radio/__stand__/examples/RadioExampleSize/RadioExampleSize.tsx
  src/components/Radio/__stand__/examples/RadioExampleStatus/RadioExampleStatus.tsx
  src/components/Radio/__stand__/examples/RadioExampleUse/RadioExampleUse.tsx
  src/components/Radio/__stand__/examples/RadioExampleView/RadioExampleView.tsx
Labels: docs

#2528 docs(custom): file
  src/components/File/__stand__/File.design.stand.mdx
  src/components/File/__stand__/File.dev.stand.mdx
  src/components/File/__stand__/File.image.svg
  src/components/File/__stand__/File.stand.mdx
  src/components/File/__stand__/File.stand.tsx
  src/components/File/__stand__/examples/FileExampleExtension/FileExampleExtension.tsx
  src/components/File/__stand__/examples/FileExampleLoading/FileExampleLoading.tsx
  src/components/File/__stand__/examples/FileExampleSize/FileExampleSize.tsx
Labels: docs

#2530 docs(custom): grid
  src/components/Grid/__stand__/Grid.design.stand.mdx
  src/components/Grid/__stand__/Grid.dev.stand.mdx
  src/components/Grid/__stand__/Grid.image.svg
  src/components/Grid/__stand__/Grid.stand.mdx
  src/components/Grid/__stand__/Grid.stand.tsx
  src/components/Grid/__stand__/examples/GridExampleAlign/GridExampleAlign.css
  src/components/Grid/__stand__/examples/GridExampleAlign/GridExampleAlign.tsx
  src/components/Grid/__stand__/examples/GridExampleBreakpoints/GridExampleBreakpoints.css
  src/components/Grid/__stand__/examples/GridExampleBreakpoints/GridExampleBreakpoints.tsx
  src/components/Grid/__stand__/examples/GridExampleCols/GridExampleCols.css
  src/components/Grid/__stand__/examples/GridExampleCols/GridExampleCols.tsx
  src/components/Grid/__stand__/examples/GridExampleGap/GridExampleGap.css
  src/components/Grid/__stand__/examples/GridExampleGap/GridExampleGap.tsx
  src/components/Grid/__stand__/examples/GridItemExampleBreakpoints/GridItemExampleBreakpoints.css
  src/components/Grid/__stand__/examples/GridItemExampleBreakpoints/GridItemExampleBreakpoints.tsx
  src/components/Grid/__stand__/examples/GridItemExampleCol/GridItemExampleCol.css
  src/components/Grid/__stand__/examples/GridItemExampleCol/GridItemExampleCol.tsx
  src/components/Grid/__stand__/examples/GridItemExampleColStart/GridItemExampleColStart.css
  src/components/Grid/__stand__/examples/GridItemExampleColStart/GridItemExampleColStart.tsx
  src/components/Grid/__stand__/examples/GridItemExampleOrder/GridItemExampleOrder.css
  src/components/Grid/__stand__/examples/GridItemExampleOrder/GridItemExampleOrder.tsx
  src/components/Grid/__stand__/examples/GridItemExampleRow/GridItemExampleRow.css
  src/components/Grid/__stand__/examples/GridItemExampleRow/GridItemExampleRow.tsx
  src/components/Grid/__stand__/examples/GridItemExampleRowStart/GridItemExampleRowStart.css
  src/components/Grid/__stand__/examples/GridItemExampleRowStart/GridItemExampleRowStart.tsx
Labels: docs

#2531 docs(custom): filefield
  src/components/FileField/__stand__/FileField.design.stand.mdx
  src/components/FileField/__stand__/FileField.dev.stand.mdx
  src/components/FileField/__stand__/FileField.image.svg
  src/components/FileField/__stand__/FileField.stand.mdx
  src/components/FileField/__stand__/FileField.stand.tsx
  src/components/FileField/__stand__/examples/FileFieldExampleRenderProp/FileFieldExampleRenderProp.tsx
  src/components/FileField/__stand__/examples/FileFieldExampleWithoutRenderProp/FileFieldExampleWithoutRenderProp.tsx
Labels: docs

#2532 docs(custom): progressSpin
  src/components/ProgressSpin/__stand__/ProgressSpin.design.stand.mdx
  src/components/ProgressSpin/__stand__/ProgressSpin.dev.stand.mdx
  src/components/ProgressSpin/__stand__/ProgressSpin.image.svg
  src/components/ProgressSpin/__stand__/ProgressSpin.stand.mdx
  src/components/ProgressSpin/__stand__/ProgressSpin.stand.tsx
  src/components/ProgressSpin/__stand__/examples/ProgressSpinExampleProgress/ProgressSpinExampleProgress.tsx
  src/components/ProgressSpin/__stand__/examples/ProgressSpinExampleSize/ProgressSpinExampleSize.tsx
Labels: docs

#2533 docs(custom): header
  src/components/Header/__stand__/Header.design.stand.mdx
  src/components/Header/__stand__/Header.dev.stand.mdx
  src/components/Header/__stand__/Header.image.svg
  src/components/Header/__stand__/Header.stand.mdx
  src/components/Header/__stand__/Header.stand.tsx
  src/components/Header/__stand__/examples/HeaderButtonExample/HeaderButtonExample.css
  src/components/Header/__stand__/examples/HeaderButtonExample/HeaderButtonExample.tsx
  src/components/Header/__stand__/examples/HeaderFullExample/HeaderFullExample.css
  src/components/Header/__stand__/examples/HeaderFullExample/HeaderFullExample.tsx
  src/components/Header/__stand__/examples/HeaderLoginExample/HeaderLoginExample.css
  src/components/Header/__stand__/examples/HeaderLoginExample/HeaderLoginExample.tsx
  src/components/Header/__stand__/examples/HeaderMenuExample/HeaderMenuExample.css
  src/components/Header/__stand__/examples/HeaderMenuExample/HeaderMenuExample.tsx
  src/components/Header/__stand__/examples/HeaderMinifyLoginExample/HeaderMinifyLoginExample.css
  src/components/Header/__stand__/examples/HeaderMinifyLoginExample/HeaderMinifyLoginExample.tsx
  src/components/Header/__stand__/examples/HeaderWithLogoExample/HeaderWithLogoExample.css
  src/components/Header/__stand__/examples/HeaderWithLogoExample/HeaderWithLogoExample.tsx
  src/components/Header/__stand__/examples/HeaderWithoutMenuExample/HeaderWithoutMenuExample.css
  src/components/Header/__stand__/examples/HeaderWithoutMenuExample/HeaderWithoutMenuExample.tsx
  src/components/Header/__stand__/examples/HeaderWithoutSearchExample/HeaderWithoutSearchExample.css
  src/components/Header/__stand__/examples/HeaderWithoutSearchExample/HeaderWithoutSearchExample.tsx
Labels: docs

#2534 docs(custom): progressLine
  src/components/ProgressLine/__stand__/ProgressLine.design.stand.mdx
  src/components/ProgressLine/__stand__/ProgressLine.dev.stand.mdx
  src/components/ProgressLine/__stand__/ProgressLine.image.svg
  src/components/ProgressLine/__stand__/ProgressLine.stand.mdx
  src/components/ProgressLine/__stand__/ProgressLine.stand.tsx
  src/components/ProgressLine/__stand__/examples/ProgressLineExampleMode/ProgressLineExampleMode.tsx
  src/components/ProgressLine/__stand__/examples/ProgressLineExampleSize/ProgressLineExampleSize.tsx
Labels: docs

#2525 docs(custom): fieldgroup
  src/components/FieldGroup/__stand__/FieldGroup.design.stand.mdx
  src/components/FieldGroup/__stand__/FieldGroup.dev.stand.mdx
  src/components/FieldGroup/__stand__/FieldGroup.image.svg
  src/components/FieldGroup/__stand__/FieldGroup.stand.mdx
  src/components/FieldGroup/__stand__/FieldGroup.stand.tsx
  src/components/FieldGroup/__stories__/examples/FieldGroupExample/FieldGroupExample.tsx
  src/components/FieldGroup/__stories__/examples/FieldGroupExampleForm/FieldGroupExampleForm.tsx
  src/components/FieldGroup/__stories__/examples/FieldGroupExampleSize/FieldGroupExampleSize.tsx
Labels: docs

#2536 docs(custom): pagination
  src/components/Pagination/__stand__/Pagination.design.stand.mdx
  src/components/Pagination/__stand__/Pagination.dev.stand.mdx
  src/components/Pagination/__stand__/Pagination.image.svg
  src/components/Pagination/__stand__/Pagination.stand.mdx
  src/components/Pagination/__stand__/Pagination.stand.tsx
  src/components/Pagination/__stand__/examples/PaginationExample/PaginationExample.tsx
Labels: docs

#2538 docs(custom): informer
  src/components/Informer/__stand__/Informer.design.stand.mdx
  src/components/Informer/__stand__/Informer.dev.stand.mdx
  src/components/Informer/__stand__/Informer.image.svg
  src/components/Informer/__stand__/Informer.stand.mdx
  src/components/Informer/__stand__/Informer.stand.tsx
  src/components/Informer/__stand__/examples/InformerExampleBasic/InformerExampleBasic.tsx
  src/components/Informer/__stand__/examples/InformerExampleIcon/InformerExampleIcon.tsx
  src/components/Informer/__stand__/examples/InformerExampleSize/InformerExampleSize.tsx
  src/components/Informer/__stand__/examples/InformerExampleText/InformerExampleText.tsx
  src/components/Informer/__stand__/examples/InformerExampleType/InformerExampleType.tsx
  src/components/Informer/__stand__/examples/InformerExampleView/InformerExampleView.tsx
Labels: docs

#2539 docs(custom): modal
  src/components/Modal/__stand__/Modal.design.stand.mdx
  src/components/Modal/__stand__/Modal.dev.stand.mdx
  src/components/Modal/__stand__/Modal.image.svg
  src/components/Modal/__stand__/Modal.stand.mdx
  src/components/Modal/__stand__/Modal.stand.tsx
  src/components/Modal/__stand__/examples/ModalExample/ModalExample.css
  src/components/Modal/__stand__/examples/ModalExample/ModalExample.tsx
  src/components/Modal/__stand__/examples/ModalExampleZIndex/ModalExampleZIndex.tsx
Labels: docs

#2540 docs(custom): loader
  src/components/Loader/__stand__/Loader.design.stand.mdx
  src/components/Loader/__stand__/Loader.dev.stand.mdx
  src/components/Loader/__stand__/Loader.image.svg
  src/components/Loader/__stand__/Loader.stand.mdx
  src/components/Loader/__stand__/Loader.stand.tsx
  src/components/Loader/__stand__/examples/LoaderExampleSize/LoaderExampleSize.tsx
Labels: docs

#2506 docs(custom): collapsegroup
  src/components/CollapseGroup/__stand__/CollapseGroup.design.stand.mdx
  src/components/CollapseGroup/__stand__/CollapseGroup.dev.stand.mdx
  src/components/CollapseGroup/__stand__/CollapseGroup.image.svg
  src/components/CollapseGroup/__stand__/CollapseGroup.stand.mdx
  src/components/CollapseGroup/__stand__/CollapseGroup.stand.tsx
  src/components/CollapseGroup/__stories__/examples/CollapseGroupExampleControl/CollapseGroupExampleControl.tsx
  src/components/CollapseGroup/__stories__/examples/CollapseGroupExampleIsAccordion/CollapseGroupExampleIsAccordion.tsx
  src/components/CollapseGroup/__stories__/examples/CollapseGroupExampleOwnType/CollapseGroupExampleOwnType.tsx
  src/components/CollapseGroup/__stories__/examples/CollapseGroupExampleSimple/CollapseGroupExampleSimple.tsx
Labels: docs

#2507 docs(custom): combobox
  src/components/Combobox/__stand__/Combobox.design.stand.mdx
  src/components/Combobox/__stand__/Combobox.dev.stand.mdx
  src/components/Combobox/__stand__/Combobox.image.svg
  src/components/Combobox/__stand__/Combobox.stand.mdx
  src/components/Combobox/__stand__/Combobox.stand.tsx
  src/components/Combobox/__stories__/examples/ComboboxExampleCreate/ComboboxExampleCreate.tsx
  src/components/Combobox/__stories__/examples/ComboboxExampleCustomTypes/ComboboxExampleCustomTypes.tsx
  src/components/Combobox/__stories__/examples/ComboboxExampleDisabled/ComboboxExampleDisabled.tsx
  src/components/Combobox/__stories__/examples/ComboboxExampleDisabledItem/ComboboxExampleDisabledItem.tsx
  src/components/Combobox/__stories__/examples/ComboboxExampleForm/ComboboxExampleForm.tsx
  src/components/Combobox/__stories__/examples/ComboboxExampleGroups/ComboboxExampleGroups.tsx
  src/components/Combobox/__stories__/examples/ComboboxExampleItems/ComboboxExampleItems.tsx
  src/components/Combobox/__stories__/examples/ComboboxExampleLabel/ComboboxExampleLabel.tsx
  src/components/Combobox/__stories__/examples/ComboboxExampleMultiple/ComboboxExampleMultiple.tsx
  src/components/Combobox/__stories__/examples/ComboboxExampleOnInputChange/ComboboxExampleOnInputChange.tsx
  src/components/Combobox/__stories__/examples/ComboboxExamplePlaceholder/ComboboxExamplePlaceholder.tsx
  src/components/Combobox/__stories__/examples/ComboboxExampleRenderItem/ComboboxExampleRenderItem.tsx
  src/components/Combobox/__stories__/examples/ComboboxExampleRenderValue/ComboboxExampleRenderValue.tsx
  src/components/Combobox/__stories__/examples/ComboboxExampleSize/ComboboxExampleSize.tsx
  src/components/Combobox/__stories__/examples/ComboboxExampleStatus/ComboboxExampleStatus.tsx
  src/components/Combobox/__stories__/examples/ComboboxExampleView/ComboboxExampleView.tsx
Labels: docs

#2508 docs(custom): tabsDeprecates
  src/components/TabsDeprecated/__stand__/Tabs.image.svg
  src/components/TabsDeprecated/__stand__/TabsDeprecated.design.stand.mdx
  src/components/TabsDeprecated/__stand__/TabsDeprecated.dev.stand.mdx
  src/components/TabsDeprecated/__stand__/TabsDeprecated.stand.mdx
  src/components/TabsDeprecated/__stand__/TabsDeprecated.stand.tsx
  src/components/TabsDeprecated/__stand__/examples/TabsExample/TabsExample.tsx
  src/components/TabsDeprecated/__stand__/examples/TabsExampleFitModeDropdown/TabsExampleFitModeDropdown.tsx
  src/components/TabsDeprecated/__stand__/examples/TabsExampleFitModeScroll/TabsExampleFitModeScroll.tsx
  src/components/TabsDeprecated/__stand__/examples/TabsExampleIcon/TabsExampleIcon.tsx
  src/components/TabsDeprecated/__stand__/examples/TabsExampleLinePosition/TabsExampleLinePosition.tsx
  src/components/TabsDeprecated/__stand__/examples/TabsExampleRenderItem/TabsExampleRenderItem.tsx
  src/components/TabsDeprecated/__stand__/examples/TabsExampleSize/TabsExampleSize.tsx
  src/components/TabsDeprecated/__stand__/examples/TabsExampleView/TabsExampleView.tsx
Labels: docs

#2510 docs(custom): switchGroup
  src/components/SwitchGroup/__stand__/SwitchGroup.design.stand.mdx
  src/components/SwitchGroup/__stand__/SwitchGroup.dev.stand.mdx
  src/components/SwitchGroup/__stand__/SwitchGroup.image.svg
  src/components/SwitchGroup/__stand__/SwitchGroup.stand.mdx
  src/components/SwitchGroup/__stand__/SwitchGroup.stand.tsx
  src/components/SwitchGroup/__stand__/examples/SwitchGroupExampleDirection/SwitchGroupExampleDirection.tsx
  src/components/SwitchGroup/__stand__/examples/SwitchGroupExampleDisabled/SwitchGroupExampleDisabled.tsx
  src/components/SwitchGroup/__stand__/examples/SwitchGroupExampleSize/SwitchGroupExampleSize.tsx
  src/components/SwitchGroup/__stand__/examples/SwitchGroupExampleView/SwitchGroupExampleView.tsx
Labels: docs

#2512 docs(custom): switch
  src/components/Switch/__stand__/Switch.dev.stand.mdx
  src/components/Switch/__stand__/Switch.image.svg
  src/components/Switch/__stand__/Switch.stand.mdx
  src/components/Switch/__stand__/Switch.stand.tsx
  src/components/Switch/__stand__/examples/SwitchExampleAlign/SwitchExampleAlign.tsx
  src/components/Switch/__stand__/examples/SwitchExampleName/SwitchExampleName.tsx
  src/components/Switch/__stand__/examples/SwitchExampleSize/SwitchExampleSize.tsx
  src/components/Switch/__stand__/examples/SwitchExampleStatus/SwitchExampleStatus.tsx
  src/components/Switch/__stand__/examples/SwitchExampleView/SwitchExampleView.tsx
Labels: docs

#2513 Docs/steps deprecated
  src/components/StepsDeprecated/__stand__/Steps.image.svg
  src/components/StepsDeprecated/__stand__/StepsDeprecated.design.stand.mdx
  src/components/StepsDeprecated/__stand__/StepsDeprecated.dev.stand.mdx
  src/components/StepsDeprecated/__stand__/StepsDeprecated.stand.mdx
  src/components/StepsDeprecated/__stand__/StepsDeprecated.stand.tsx
  src/components/StepsDeprecated/__stand__/examples/ExampleStepsAdaptive/ExampleStepsAdaptive.tsx
  src/components/StepsDeprecated/__stand__/examples/ExampleStepsCompleted/ExampleStepsCompleted.tsx
  src/components/StepsDeprecated/__stand__/examples/ExampleStepsContent/ExampleStepsContent.tsx
  src/components/StepsDeprecated/__stand__/examples/ExampleStepsDisabled/ExampleStepsDisabled.tsx
  src/components/StepsDeprecated/__stand__/examples/ExampleStepsSize/ExampleStepsSize.tsx
  src/components/StepsDeprecated/__stand__/examples/ExampleStepsSkipped/ExampleStepsSkipped.tsx
  src/components/StepsDeprecated/__stand__/examples/ExampleStepsValue/ExampleStepsValue.tsx
Labels: docs

#2514 docs(custom): steps
  src/components/Steps/__stand__/Steps.design.stand.mdx
  src/components/Steps/__stand__/Steps.dev.stand.mdx
  src/components/Steps/__stand__/Steps.image.svg
  src/components/Steps/__stand__/Steps.stand.mdx
  src/components/Steps/__stand__/Steps.stand.tsx
  src/components/Steps/__stand__/examples/ExampleStepsAdaptive/ExampleStepsAdaptive.tsx
  src/components/Steps/__stand__/examples/ExampleStepsCompleted/ExampleStepsCompleted.tsx
  src/components/Steps/__stand__/examples/ExampleStepsContent/ExampleStepsContent.tsx
  src/components/Steps/__stand__/examples/ExampleStepsDisabled/ExampleStepsDisabled.tsx
  src/components/Steps/__stand__/examples/ExampleStepsSize/ExampleStepsSize.tsx
  src/components/Steps/__stand__/examples/ExampleStepsSkipped/ExampleStepsSkipped.tsx
  src/components/Steps/__stand__/examples/ExampleStepsValue/ExampleStepsValue.tsx
Labels: docs

#2515 docs(custom): add doc for SnackBar
  src/components/SnackBar/__stand__/SnackBar.design.stand.mdx
  src/components/SnackBar/__stand__/SnackBar.dev.stand.mdx
  src/components/SnackBar/__stand__/SnackBar.image.svg
  src/components/SnackBar/__stand__/SnackBar.stand.mdx
  src/components/SnackBar/__stand__/SnackBar.stand.tsx
  src/components/SnackBar/__stand__/examples/SnackBarExampleAdaptive/SnackBarExampleAdaptive.tsx
  src/components/SnackBar/__stand__/examples/SnackBarExampleButtons/SnackBarExampleButtons.css
  src/components/SnackBar/__stand__/examples/SnackBarExampleButtons/SnackBarExampleButtons.tsx
  src/components/SnackBar/__stand__/examples/SnackBarExampleIcon/SnackBarExampleIcon.css
  src/components/SnackBar/__stand__/examples/SnackBarExampleIcon/SnackBarExampleIcon.tsx
  src/components/SnackBar/__stand__/examples/SnackBarExampleSimple/SnackBarExampleSimple.css
  src/components/SnackBar/__stand__/examples/SnackBarExampleSimple/SnackBarExampleSimple.tsx
  src/components/SnackBar/__stand__/examples/SnackBarExampleStatus/SnackBarExampleStatus.css
  src/components/SnackBar/__stand__/examples/SnackBarExampleStatus/SnackBarExampleStatus.tsx
  src/components/SnackBar/__stand__/examples/SnackBarExampleText/SnackBarExampleText.css
  src/components/SnackBar/__stand__/examples/SnackBarExampleText/SnackBarExampleText.tsx
  src/components/SnackBar/__stand__/examples/SnackBarExampleTimer/SnackBarExampleTimer.css
  src/components/SnackBar/__stand__/examples/SnackBarExampleTimer/SnackBarExampleTimer.tsx
Labels: docs

#2516 docs(custom): slider
  src/components/Slider/__stand__/Slider.design.stand.mdx
  src/components/Slider/__stand__/Slider.dev.stand.mdx
  src/components/Slider/__stand__/Slider.image.svg
  src/components/Slider/__stand__/Slider.stand.mdx
  src/components/Slider/__stand__/Slider.stand.tsx
  src/components/Slider/__stand__/examples/SliderExampleBasic/SliderExampleBasic.tsx
  src/components/Slider/__stand__/examples/SliderExampleContent/SliderExampleContent.tsx
  src/components/Slider/__stand__/examples/SliderExampleDisabled/SliderExampleDisabled.tsx
  src/components/Slider/__stand__/examples/SliderExampleLabel/SliderExampleLabel.tsx
  src/components/Slider/__stand__/examples/SliderExampleMinMax/SliderExampleMinMax.tsx
  src/components/Slider/__stand__/examples/SliderExampleRange/SliderExampleRange.tsx
  src/components/Slider/__stand__/examples/SliderExampleSize/SliderExampleSize.css
  src/components/Slider/__stand__/examples/SliderExampleSize/SliderExampleSize.tsx
  src/components/Slider/__stand__/examples/SliderExampleStatus/SliderExampleStatus.css
  src/components/Slider/__stand__/examples/SliderExampleStatus/SliderExampleStatus.tsx
  src/components/Slider/__stand__/examples/SliderExampleStep/SliderExampleStep.tsx
  src/components/Slider/__stand__/examples/SliderExampleTooltip/SliderExampleTooltip.tsx
  src/components/Slider/__stand__/examples/SliderExampleTooltipFormatter/SliderExampleTooltipFormatter.tsx
  src/components/Slider/__stand__/examples/SliderExampleView/SliderExampleView.tsx
Labels: docs

#2519 docs(custom): select
  src/components/Select/__stand__/Select.design.stand.mdx
  src/components/Select/__stand__/Select.dev.stand.mdx
  src/components/Select/__stand__/Select.image.svg
  src/components/Select/__stand__/Select.stand.mdx
  src/components/Select/__stand__/Select.stand.tsx
  src/components/Select/__stand__/examples/SelectExampleCustomTypes/SelectExampleCustomTypes.tsx
  src/components/Select/__stand__/examples/SelectExampleDisabled/SelectExampleDisabled.tsx
  src/components/Select/__stand__/examples/SelectExampleDisabledItem/SelectExampleDisabledItem.tsx
  src/components/Select/__stand__/examples/SelectExampleForm/SelectExampleForm.tsx
  src/components/Select/__stand__/examples/SelectExampleGroups/SelectExampleGroups.tsx
  src/components/Select/__stand__/examples/SelectExampleItems/SelectExampleItems.tsx
  src/components/Select/__stand__/examples/SelectExampleLabel/SelectExampleLabel.tsx
  src/components/Select/__stand__/examples/SelectExamplePlaceholder/SelectExamplePlaceholder.tsx
  src/components/Select/__stand__/examples/SelectExampleRenderItem/SelectExampleRenderItem.css
  src/components/Select/__stand__/examples/SelectExampleRenderItem/SelectExampleRenderItem.tsx
  src/components/Select/__stand__/examples/SelectExampleRenderValue/SelectExampleRenderValue.tsx
  src/components/Select/__stand__/examples/SelectExampleSize/SelectExampleSize.tsx
  src/components/Select/__stand__/examples/SelectExampleStatus/SelectExampleStatus.tsx
  src/components/Select/__stand__/examples/SelectExampleView/SelectExampleView.tsx
Labels: docs

#2520 docs(custom): datepicker
  src/components/DatePicker/__stand__/DatePicker.design.stand.mdx
  src/components/DatePicker/__stand__/DatePicker.dev.stand.mdx
  src/components/DatePicker/__stand__/DatePicker.image.svg
  src/components/DatePicker/__stand__/DatePicker.stand.mdx
  src/components/DatePicker/__stand__/DatePicker.stand.tsx
  src/components/DatePicker/__stories__/examples/DatePickerExampleAdditionalControls/DatePickerExampleAdditionalControls.tsx
  src/components/DatePicker/__stories__/examples/DatePickerExampleCaption/DatePickerExampleCaption.tsx
  src/components/DatePicker/__stories__/examples/DatePickerExampleOnError/DatePickerExampleOnError.tsx
  src/components/DatePicker/__stories__/examples/DatePickerExampleRequired/DatePickerExampleRequired.tsx
  src/components/DatePicker/__stories__/examples/DatePickerExampleStatus/DatePickerExampleStatus.tsx
  src/components/DatePicker/__stories__/examples/DatePickerExampleWithClearButton/DatePickerExampleWithClearButton.tsx
Labels: docs

#2543 docs(custom): checkbox-deprecated
  src/components/CheckboxGroupDeprecated/__stand__/CheckboxGroup.design.stand.mdx
  src/components/CheckboxGroupDeprecated/__stand__/CheckboxGroup.dev.stand.mdx
  src/components/CheckboxGroupDeprecated/__stand__/CheckboxGroup.image.svg
  src/components/CheckboxGroupDeprecated/__stand__/CheckboxGroup.stand.mdx
  src/components/CheckboxGroupDeprecated/__stand__/CheckboxGroup.stand.tsx
  src/components/CheckboxGroupDeprecated/__stand__/examples/CheckboxGroupExampleDirection/CheckboxGroupExampleDirection.tsx
  src/components/CheckboxGroupDeprecated/__stand__/examples/CheckboxGroupExampleDisabled/CheckboxGroupExampleDisabled.tsx
  src/components/CheckboxGroupDeprecated/__stand__/examples/CheckboxGroupExampleName/CheckboxGroupExampleName.tsx
  src/components/CheckboxGroupDeprecated/__stand__/examples/CheckboxGroupExampleSize/CheckboxGroupExampleSize.tsx
  src/components/CheckboxGroupDeprecated/__stand__/examples/CheckboxGroupExampleView/CheckboxGroupExampleView.tsx
Labels: docs

#2544 docs(custom): chdeckboxgroup
  src/components/CheckboxGroup/__stand__/CheckboxGroup.dev.stand.mdx
  src/components/CheckboxGroup/__stand__/CheckboxGroup.stand.mdx
Labels: docs

#2556 docs(custom): breadcrumbs_deprecated
  src/components/BreadcrumbsDeprecated/__stand__/Breadcrumbs.design.stand.mdx
  src/components/BreadcrumbsDeprecated/__stand__/Breadcrumbs.dev.stand.mdx
  src/components/BreadcrumbsDeprecated/__stand__/Breadcrumbs.image.svg
  src/components/BreadcrumbsDeprecated/__stand__/Breadcrumbs.stand.mdx
  src/components/BreadcrumbsDeprecated/__stand__/Breadcrumbs.stand.tsx
  src/components/BreadcrumbsDeprecated/__stand__/examples/BreadcrumbsExample/BreadcrumbsExample.tsx
Labels: docs

#2557 docs(custom): breadcrumbs
  src/components/Breadcrumbs/__stand__/Breadcrumbs.design.stand.mdx
  src/components/Breadcrumbs/__stand__/Breadcrumbs.dev.stand.mdx
  src/components/Breadcrumbs/__stand__/Breadcrumbs.image.svg
  src/components/Breadcrumbs/__stand__/Breadcrumbs.stand.mdx
  src/components/Breadcrumbs/__stand__/Breadcrumbs.stand.tsx
  src/components/Breadcrumbs/__stand__/examples/BreadcrumbsExample/BreadcrumbsExample.tsx
Labels: docs

#2560 docs(custom): choicegroup_deprecated
  src/components/ChoiceGroupDeprecated/__stand__/ChoiceGroup.design.stand.mdx
  src/components/ChoiceGroupDeprecated/__stand__/ChoiceGroup.dev.stand.mdx
  src/components/ChoiceGroupDeprecated/__stand__/ChoiceGroup.image.svg
  src/components/ChoiceGroupDeprecated/__stand__/ChoiceGroup.stand.mdx
  src/components/ChoiceGroupDeprecated/__stand__/ChoiceGroup.stand.tsx
  src/components/ChoiceGroupDeprecated/__stand__/examples/ChoiceGroupExampleDisabled/ChoiceGroupExampleDisabled.tsx
  src/components/ChoiceGroupDeprecated/__stand__/examples/ChoiceGroupExampleForm/ChoiceGroupExampleForm.tsx
  src/components/ChoiceGroupDeprecated/__stand__/examples/ChoiceGroupExampleIcon/ChoiceGroupExampleIcon.tsx
  src/components/ChoiceGroupDeprecated/__stand__/examples/ChoiceGroupExampleMultiple/ChoiceGroupExampleMultiple.tsx
  src/components/ChoiceGroupDeprecated/__stand__/examples/ChoiceGroupExampleSize/ChoiceGroupExampleSize.tsx
  src/components/ChoiceGroupDeprecated/__stand__/examples/ChoiceGroupExampleSomeDisabled/ChoiseGroupExampleSomeDisabled.tsx
  src/components/ChoiceGroupDeprecated/__stand__/examples/ChoiceGroupExampleSwitch/ChoiceGroupExampleSwitch.tsx
  src/components/ChoiceGroupDeprecated/__stand__/examples/ChoiceGroupExampleText/ChoiceGroupExampleText.tsx
  src/components/ChoiceGroupDeprecated/__stand__/examples/ChoiceGroupExampleTextOverflow/ChoiceGroupExampleTextOverflow.tsx
  src/components/ChoiceGroupDeprecated/__stand__/examples/ChoiceGroupExampleView/ChoiceGroupExampleView.tsx
  src/components/ChoiceGroupDeprecated/__stand__/examples/ChoiceGroupExampleWidth/ChoiceGroupExampleWidth.tsx
  src/components/ChoiceGroupDeprecated/__stories__/examples/ChoiceGroupExampleAdaptive/ChoiceGroupExampleAdaptive.tsx
  src/components/ChoiceGroupDeprecated/__stories__/examples/ChoiceGroupExampleAdaptive/ChoiceGroupExampleAdaptiveScroll.css
Labels: docs

#2545 docs(custom): withTooltip
  src/hocs/withTooltip/__stand__/examples/WithTooltipExampleMode/WithTooltipExampleMode.tsx
  src/hocs/withTooltip/__stand__/examples/WithTooltipExampleProps/WithTooltipExampleProps.tsx
  src/hocs/withTooltip/__stand__/examples/WithTooltipExampleSize/WithTooltipExampleSize.tsx
  src/hocs/withTooltip/__stand__/examples/WithTooltipExampleText/WithTooltipExampleText.tsx
  src/hocs/withTooltip/__stand__/withTooltip.dev.stand.mdx
  src/hocs/withTooltip/__stand__/withTooltip.stand.mdx
  src/hocs/withTooltip/__stand__/withTooltip.stand.tsx
Labels: docs

#2546 docs(custom): useChoiceGroup
  src/hooks/useChoiceGroup/__stand__/useChocieGroup.stand.mdx
  src/hooks/useChoiceGroup/__stand__/useChoiceGroup.dev.stand.mdx
  src/hooks/useChoiceGroup/__stand__/useChoiceGroup.stand.tsx
Labels: docs

#2547 docs(custom): useChoiceGroupIndexed
  src/hooks/useChoiceGroupIndexed/__stand__/useChoiceGroupIndexed.dev.stand.mdx
  src/hooks/useChoiceGroupIndexed/__stand__/useChoiceGroupIndexed.stand.mdx
  src/hooks/useChoiceGroupIndexed/__stand__/useChoiceGroupIndexed.stand.tsx
Labels: docs

#2548 docs(custom): useClickOutside
  src/hooks/useClickOutside/__stand__/useClickOutside.dev.stand.mdx
  src/hooks/useClickOutside/__stand__/useClickOutside.stand.mdx
  src/hooks/useClickOutside/__stand__/useClickOutside.stand.tsx
Labels: docs

#2549 docs(custom): useDebounce
  src/hooks/useDebounce/__stand__/examples/UseDebounceExample/UseDebounceExample.css
  src/hooks/useDebounce/__stand__/examples/UseDebounceExample/UseDebounceExample.tsx
  src/hooks/useDebounce/__stand__/useDebounce.dev.stand.mdx
  src/hooks/useDebounce/__stand__/useDebounce.stand.mdx
  src/hooks/useDebounce/__stand__/useDebounce.stand.tsx
Labels: docs

#2550 docs(custom): useForkRef
  src/hooks/useForkRef/__stand__/useForkRef.dev.stand.mdx
  src/hooks/useForkRef/__stand__/useForkRef.stand.mdx
  src/hooks/useForkRef/__stand__/useForkRef.stand.tsx
Labels: docs

#2551 docs(custom): useBreakpoints
  src/hooks/useBreakpoints/__stand__/useBreakpoints.dev.stand.mdx
  src/hooks/useBreakpoints/__stand__/useBreakpoints.stand.mdx
  src/hooks/useBreakpoints/__stand__/useBreakpoints.stand.tsx
Labels: docs

#2553 docs(custom): useHideElementsInLine
  src/hooks/useHideElementsInLine/__stand__/examples/ExampleUseHideElementsInLine/ExampleUseHideElementsInLine.css
  src/hooks/useHideElementsInLine/__stand__/examples/ExampleUseHideElementsInLine/ExampleUseHideElementsInLine.tsx
  src/hooks/useHideElementsInLine/__stand__/useHideElementsInLine.dev.stand.mdx
  src/hooks/useHideElementsInLine/__stand__/useHideElementsInLine.stand.mdx
  src/hooks/useHideElementsInLine/__stand__/useHideElementsInLine.stand.tsx
Labels: docs

#2554 docs(custom): useRefs
  src/hooks/useRefs/__stand__/useRefs.dev.stand.mdx
  src/hooks/useRefs/__stand__/useRefs.stand.mdx
  src/hooks/useRefs/__stand__/useRefs.stand.tsx
Labels: docs

#2563 docs: add docs for ContextMenuDeprecated
  src/components/ContextMenuDeprecated/__stand__/ContextMenu.design.stand.mdx
  src/components/ContextMenuDeprecated/__stand__/ContextMenu.dev.stand.mdx
  src/components/ContextMenuDeprecated/__stand__/ContextMenu.image.svg
  src/components/ContextMenuDeprecated/__stand__/ContextMenu.stand.mdx
  src/components/ContextMenuDeprecated/__stand__/ContextMenu.stand.tsx
  src/components/ContextMenuDeprecated/__stand__/examples/ContextMenuExampleGroups/ContextMenuExampleGroups.css
  src/components/ContextMenuDeprecated/__stand__/examples/ContextMenuExampleGroups/ContextMenuExampleGroups.tsx
  src/components/ContextMenuDeprecated/__stand__/examples/ContextMenuExampleOutsideClick/ContextMenuExampleOutsideClick.css
  src/components/ContextMenuDeprecated/__stand__/examples/ContextMenuExampleOutsideClick/ContextMenuExampleOutsideClick.tsx
  src/components/ContextMenuDeprecated/__stand__/examples/ContextMenuExampleSide/ContextMenuExampleSide.css
  src/components/ContextMenuDeprecated/__stand__/examples/ContextMenuExampleSide/ContextMenuExampleSide.tsx
  src/components/ContextMenuDeprecated/__stand__/examples/ContextMenuExampleSimple/ContextMenuExampleSimple.css
  src/components/ContextMenuDeprecated/__stand__/examples/ContextMenuExampleSimple/ContextMenuExampleSimple.tsx
  src/components/ContextMenuDeprecated/__stand__/examples/ContextMenuExampleSize/ContextMenuExampleSize.css
  src/components/ContextMenuDeprecated/__stand__/examples/ContextMenuExampleSize/ContextMenuExampleSize.tsx
  src/components/ContextMenuDeprecated/__stand__/examples/ContextMenuExampleSubMenu/ContextMenuExampleSubMenu.css
  src/components/ContextMenuDeprecated/__stand__/examples/ContextMenuExampleSubMenu/ContextMenuExampleSubMenu.tsx
Labels: docs

#2552 docs(custom): useGlobalKeys
  src/hooks/useGlobalKeys/__stand__/useGlobalKeys.dev.stand.mdx
  src/hooks/useGlobalKeys/__stand__/useGlobalKeys.stand.mdx
  src/hooks/useGlobalKeys/__stand__/useGlobalKeys.stand.tsx
Labels: docs

#2481 feat(Tabs): add xs size and fix colors
  src/components/Tabs/Line/TabsLine.css
  src/components/Tabs/Tab/TabsTab.css
  src/components/Tabs/Tab/TabsTab.tsx
  src/components/Tabs/Tabs.css
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/__stories__/Tabs.docs.mdx
  src/components/Tabs/__stories__/examples/TabsExampleSize/TabsExampleSize.tsx
  src/components/TabsCanary/Line/TabsLine.css
  src/components/TabsCanary/Tab/TabsTab.css
  src/components/TabsCanary/Tab/TabsTab.tsx
  src/components/TabsCanary/Tabs.css
  src/components/TabsCanary/__stories__/Tabs.docs.mdx
  src/components/TabsCanary/__stories__/examples/TabsExampleSize/TabsExampleSize.tsx
  src/components/TabsCanary/types.ts
Labels: feature

#2590 docs(Button): fix misprint, describe icon size
  src/components/Button/__stories__/Button.docs.mdx
Labels: docs
